(() => {
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const FILE_NAME='warrior-hub-sync.json', DEVICE_DIR='warrior-hub-sync-devices', SCHEMA=1, APP_VERSION='0.6.1';
const CALCULUS_URL='https://archive.org/details/stewart-j.-clegg-d.-watson-s.-calculus.-early-transcendentals-9ed-2020/page/425/mode/2up';
const ETHICS_URL='./resources/being-good-simon-blackburn.pdf';
const CHEM2_LAB_URL='https://canvas.wayne.edu/courses/244636/modules/items/6576907';
const AUTH_SCOPES='openid profile offline_access User.Read Files.ReadWrite';
const DEFAULT_MS_CLIENT_ID='098158b9-35ee-497c-97c2-3490353cb745';
const REMOTE_LIVE_FILE='warrior-mobile-live.json', REMOTE_COMMAND_DIR='warrior-mobile-commands', REMOTE_PUSH_FILE='warrior-mobile-push.json';
const REMOTE_POLL_MS=1800, REMOTE_STALE_MS=15000;
const MOBILE_VAPID_PUBLIC_KEY='BNRHZhm7ACH99DcUwvQAYJfx9p1QAzoyUnqjk3nFs8NlR2NF4XzB6iwh8mY__649Tcav1FywFojPVpBQBug9I6Y';
// Keep v0.1 keys intentionally: updating the PWA must not reset setup/state cache.
const CFG_KEY='warriorMobileConfigV01', CACHE_KEY='warriorMobileCloudV01', META_KEY='warriorMobileMetaV01', TIMER_KEY='warriorMobileTimerV01';
const DRAW_DB='warrior-mobile-drawing-notes-v2', DRAW_DB_VERSION=2, NOTES_FOLDER='warrior-notes-v2', NOTES_ASSETS_FOLDER='assets';
const CANVAS_W=1400, CANVAS_H=1980;
const debug=[]; const log=(event,data={})=>{debug.push({at:Date.now(),event,data});if(debug.length>600)debug.splice(0,debug.length-600)};
let cfg=loadJson(CFG_KEY,{clientId:'',folder:'WARRIOR HUB',tenant:'common'}), cloud=loadJson(CACHE_KEY,null), meta=loadJson(META_KEY,{clocks:{},deviceId:crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`,lastSyncAt:0});
// Migrate the mistaken Microsoft Services tenant ID that was saved by v0.6.0.
if(cfg.clientId==='f8cdef31-a31e-4b4a-93e4-5f571e91255a'){cfg={...cfg,clientId:DEFAULT_MS_CLIENT_ID};saveJson(CFG_KEY,cfg)}
let state=cloud?.warriorState||{}, currentView='today', selectedDay=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'][new Date().getDay()], calCursor=new Date(new Date().getFullYear(),new Date().getMonth(),1), calSelected=localDateKey(new Date());
let timer=loadJson(TIMER_KEY,{remainingMs:50*60*1000,running:false,endAt:0}), timerHandle=null, pushTimer=null, noteCloudTimer=null;
let remoteLive=null, remotePollTimer=null, remoteFetchBusy=false, remoteLastError='', remoteCommandBusy=false;
let drawCourse='', drawDate=localDateKey(new Date()), drawPages=[], activePage=null, activePageIndex=0, activePageChanged=false, drawTool='pen', drawColor='#11151d', drawWidth=4, fingerDraw=false, drawing=false, liveStroke=null, undoStack=[], redoStack=[], lastCheckpointAt=0, selectedItemId='', itemGesture=null;
let noteDbPromise=null,segmentObserver=null,segmentGrowBusy=false,lastStrokeSafetySaveAt=0; const assetBitmapCache=new Map(), assetBitmapOrder=[], assetLoadPending=new Set();

function loadJson(k,d){try{const v=localStorage.getItem(k);return v?JSON.parse(v):d}catch(_){return d}}
function saveJson(k,v){localStorage.setItem(k,JSON.stringify(v))}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function fmtDate(v,opts={month:'short',day:'numeric'}){const d=new Date(v);return Number.isFinite(+d)?new Intl.DateTimeFormat(undefined,opts).format(d):''}
function fmtTime(t){if(!t)return'';const [h,m]=String(t).split(':').map(Number),d=new Date();d.setHours(h,m||0,0,0);return new Intl.DateTimeFormat(undefined,{hour:'numeric',minute:'2-digit'}).format(d)}
function timeToMinutes(t){if(!t)return 9999;const[h,m]=String(t).split(':').map(Number);return h*60+(m||0)}
function localDateKey(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function addDays(key,n){const d=new Date(`${key}T12:00:00`);d.setDate(d.getDate()+n);return localDateKey(d)}
function isDone(a){return !!(a?.completed||a?.submitted)}
function hiddenSet(){return new Set((state.hiddenAssignments||[]).map(String))}
function openAssignments(){const h=hiddenSet(),n=Date.now();return(state.assignments||[]).filter(a=>!h.has(String(a.id))&&!isDone(a)&&(!a.dueAt||!Number.isFinite(Date.parse(a.dueAt))||Date.parse(a.dueAt)>=n)).sort((a,b)=>Date.parse(a.dueAt||'9999')-Date.parse(b.dueAt||'9999'))}
function resourceFor(a){const hay=`${a?.courseId||''} ${a?.courseName||''} ${a?.courseCode||''}`.toLowerCase();if(/(^|\D)(243235)(\D|$)|mat\s*2120|mat\s*2020|math\s*1760|calculus/.test(hay))return{label:'📘 Calculus book',url:CALCULUS_URL};if(/phi\s*1100|contemporary moral issues|moral issues/.test(hay))return{label:'📗 Being Good PDF',url:ETHICS_URL};if(/(^|\D)(244636)(\D|$)|general\s+chemistry\s+(ii|2)\s+laboratory|chem(?:istry)?\s*(ii|2).*\blab(?:oratory)?\b/.test(hay))return{label:'🧪 Chem 2 Lab',url:CHEM2_LAB_URL};return null}
function assignmentCard(a){const due=a.dueAt?Date.parse(a.dueAt):NaN,late=Number.isFinite(due)&&due<Date.now()&&!isDone(a),r=resourceFor(a);return `<div class="card clickable" data-open="${esc(a.url||'')}"><div class="title">${esc(a.title||'Assignment')}</div><div class="meta">${esc(a.courseName||a.courseCode||'Canvas')}${a.dueAt?` · ${esc(fmtDate(a.dueAt,{weekday:'short',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}))}`:''}</div><div>${a.submitted?'<span class="badge ok">submitted</span>':isDone(a)?'<span class="badge ok">done</span>':late?'<span class="badge bad">overdue</span>':'<span class="badge">open</span>'}</div><div class="assignment-actions">${r?`<a href="${esc(r.url)}" target="_blank" rel="noopener">${r.label}</a>`:''}${a.url?`<a href="${esc(a.url)}" target="_blank" rel="noopener">open ↗</a>`:''}</div></div>`}
function classCard(c){return `<div class="card class-row"><div class="class-time">${esc(fmtTime(c.startTime))}</div><div><div class="title">${esc(c.code||c.title||'Class')}</div><div class="meta">${c.endTime?`until ${esc(fmtTime(c.endTime))}`:''}${c.location?` · ${esc(c.location)}`:''}${c.instructor?` · ${esc(c.instructor)}`:''}</div></div></div>`}
function empty(s){return `<div class="empty">${esc(s)}</div>`}

function setView(name){currentView=name;$$('.tab').forEach(x=>x.classList.toggle('active',x.dataset.view===name));$$('.view').forEach(x=>x.classList.toggle('active',x.id===`view-${name}`));renderView()}
function renderView(){if(currentView==='today')renderToday();else if(currentView==='assignments')renderAssignments();else if(currentView==='calendar')renderCalendar();else if(currentView==='schedule')renderSchedule();else if(currentView==='news')renderNews();else if(currentView==='mail')renderMail();else if(currentView==='study')renderRemoteStudy();else if(currentView==='notes')renderNotes().catch(e=>noteStatus(String(e.message||e),'error'));else if(currentView==='setup')renderSetup()}
function renderAll(){const d=new Date();$('#todayLabel').textContent=new Intl.DateTimeFormat(undefined,{weekday:'long',month:'short',day:'numeric'}).format(d).toUpperCase();renderView();renderStatus()}
function renderStatus(msg){const b=$('#statusBanner');if(msg){b.textContent=msg.text;b.className=`status-banner ${msg.kind||''}`;return}if(!cfg.clientId){b.textContent='Setup required · add Microsoft client ID';b.className='status-banner'}else if(!cloud){b.textContent='Ready to sign in and sync OneDrive';b.className='status-banner'}else{b.textContent=`OneDrive cache · ${cloud.warriorState?.assignments?.length||0} assignments · ${meta.lastSyncAt?fmtDate(meta.lastSyncAt,{hour:'numeric',minute:'2-digit'}):'not synced'}`;b.className='status-banner ok'}}
function renderToday(){const now=new Date(),day=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'][now.getDay()],mins=now.getHours()*60+now.getMinutes(),classes=(state.schedule||[]).filter(c=>(c.days||[]).includes(day)&&timeToMinutes(c.endTime||c.startTime)>mins).sort((a,b)=>String(a.startTime).localeCompare(String(b.startTime)));$('#todayClassCount').textContent=classes.length?`${classes.length} left`:'';$('#todayClasses').innerHTML=classes.length?classes.map(classCard).join(''):empty('No more classes today.');const next=classes[0];$('#nextClass').innerHTML=next?`<div class="next-card"><div class="eyebrow">NEXT CLASS</div><div class="big">${esc(next.code||next.title||'Class')}</div><div class="meta">${esc(fmtTime(next.startTime))}${next.endTime?` – ${esc(fmtTime(next.endTime))}`:''}${next.location?` · ${esc(next.location)}`:''}</div></div>`:'';const due=openAssignments().slice(0,5);$('#dueSoonCount').textContent=due.length?`${due.length}`:'';$('#dueSoon').innerHTML=due.length?due.map(assignmentCard).join(''):empty('Nothing urgent.');renderTimer()}
function renderAssignments(){const f=$('#assignmentFilter').value,q=$('#assignmentSearch').value.trim().toLowerCase(),h=hiddenSet(),now=Date.now(),week=now+7*86400000;let list=(state.assignments||[]).filter(a=>!h.has(String(a.id)));if(q)list=list.filter(a=>`${a.title||''} ${a.courseName||''} ${a.courseCode||''}`.toLowerCase().includes(q));if(f==='open')list=list.filter(a=>!isDone(a)&&(!a.dueAt||Date.parse(a.dueAt)>=now));if(f==='week')list=list.filter(a=>!isDone(a)&&a.dueAt&&Date.parse(a.dueAt)>=now&&Date.parse(a.dueAt)<=week);if(f==='overdue')list=list.filter(a=>!isDone(a)&&a.dueAt&&Date.parse(a.dueAt)<now);list.sort((a,b)=>Date.parse(a.dueAt||'9999')-Date.parse(b.dueAt||'9999'));$('#assignmentList').innerHTML=list.length?list.map(assignmentCard).join(''):empty('No assignments in this view.')}
function renderCalendar(){const y=calCursor.getFullYear(),m=calCursor.getMonth();$('#calMonth').textContent=new Intl.DateTimeFormat(undefined,{month:'long',year:'numeric'}).format(calCursor);const h=hiddenSet(),as=(state.assignments||[]).filter(a=>!h.has(String(a.id))&&a.dueAt&&Number.isFinite(Date.parse(a.dueAt))),map=new Map();for(const a of as){const k=localDateKey(new Date(a.dueAt));if(!map.has(k))map.set(k,[]);map.get(k).push(a)}const first=new Date(y,m,1),start=new Date(y,m,1-first.getDay());let out='';for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const k=localDateKey(d),items=map.get(k)||[];out+=`<button class="calendar-day${d.getMonth()!==m?' outside':''}${k===calSelected?' selected':''}${k===localDateKey(new Date())?' today':''}" data-date="${k}"><span>${d.getDate()}</span><span class="dots">${items.slice(0,4).map(()=>'<i class="dot"></i>').join('')}</span></button>`}$('#calendarGrid').innerHTML=out;const sd=new Date(`${calSelected}T12:00:00`);$('#agendaDate').textContent=fmtDate(sd,{weekday:'long',month:'short',day:'numeric'});const ag=map.get(calSelected)||[];$('#calendarAgenda').innerHTML=ag.length?ag.map(assignmentCard).join(''):empty('Nothing due.')}
function renderSchedule(){const days=['Mon','Tue','Wed','Thu','Fri'];if(!days.includes(selectedDay))selectedDay=days[0];$('#dayTabs').innerHTML=days.map(d=>`<button class="${d===selectedDay?'active':''}" data-day="${d}">${d}</button>`).join('');const list=(state.schedule||[]).filter(c=>(c.days||[]).includes(selectedDay)).sort((a,b)=>String(a.startTime).localeCompare(String(b.startTime)));$('#scheduleList').innerHTML=list.length?list.map(classCard).join(''):empty(`No classes on ${selectedDay}.`)}
function courseOptions(){const by=new Map();for(const a of state.assignments||[]){const id=String(a.courseId||a.courseCode||a.courseName||'general'),name=a.courseName||a.courseCode||'General';if(!by.has(id))by.set(id,name)}for(const c of state.schedule||[]){const code=String(c.code||'').trim(),existing=[...by.entries()].find(([,name])=>code&&String(name).toLowerCase().includes(code.toLowerCase()));if(existing)continue;const id=String(c.courseId||code||c.title||'general'),name=code?`${code}${c.title&&c.title!==code?` · ${c.title}`:''}`:(c.title||'General');if(!by.has(id))by.set(id,name)}if(!by.size)by.set('general','General');return [...by.entries()].sort((a,b)=>a[1].localeCompare(b[1]))}
function preferredCourse(){const opts=courseOptions(),now=new Date(),day=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'][now.getDay()],mins=now.getHours()*60+now.getMinutes(),classes=(state.schedule||[]).filter(c=>(c.days||[]).includes(day)&&timeToMinutes(c.endTime||c.startTime)>mins).sort((a,b)=>String(a.startTime).localeCompare(String(b.startTime))),code=String(classes[0]?.code||'').trim();if(code){const hit=opts.find(([,name])=>String(name).toLowerCase().includes(code.toLowerCase()));if(hit)return hit[0]}return opts[0]?.[0]||'general'}
function isUnread(item,kind){if(item?.unread===true||item?.isUnread===true)return true;if(item?.read===true||item?.isRead===true)return false;const seen=new Set((state.previewRead?.[kind]||[]).map(String));return !seen.has(String(item?.id||''))}
function renderNews(){const list=(state.announcements||[]).slice().sort((a,b)=>Date.parse(b.postedAt||0)-Date.parse(a.postedAt||0));$('#newsList').innerHTML=list.length?list.map(a=>`<div class="card clickable" data-open="${esc(a.url||'')}"><div class="title">${esc(a.title||'Announcement')}</div><div class="meta">${esc(a.courseName||'')}${a.postedAt?` · ${esc(fmtDate(a.postedAt,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}))}`:''}</div>${isUnread(a,'announcements')?'<span class="badge warn">unread</span>':''}${a.message?`<div class="meta" style="margin-top:8px">${esc(String(a.message).slice(0,320))}</div>`:''}</div>`).join(''):empty('No announcements synced yet.')}
function renderMail(){const list=(state.mail||[]).slice().sort((a,b)=>Date.parse(b.date||b.receivedAt||b.sentAt||0)-Date.parse(a.date||a.receivedAt||a.sentAt||0));$('#mailList').innerHTML=list.length?list.map(m=>`<div class="card clickable" data-open="${esc(m.url||'')}"><div class="title">${esc(m.subject||m.title||'Mail')}</div><div class="meta">${esc(m.from||m.sender||'')}${m.receivedAt||m.date?` · ${esc(fmtDate(m.receivedAt||m.date,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}))}`:''}</div>${isUnread(m,'mail')?'<span class="badge warn">unread</span>':''}${m.important?'<span class="badge bad">important</span>':''}${m.preview||m.snippet?`<div class="meta" style="margin-top:8px">${esc(String(m.preview||m.snippet).slice(0,320))}</div>`:''}</div>`).join(''):empty('No mail synced yet.')}

/* ---------- durable infinite drawing notes ---------- */
function noteDb(){
  if(noteDbPromise)return noteDbPromise;
  noteDbPromise=new Promise((res,rej)=>{const r=indexedDB.open(DRAW_DB,DRAW_DB_VERSION);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains('pages')){const st=db.createObjectStore('pages',{keyPath:'key'});st.createIndex('courseDate',['courseKey','dateKey'],{unique:false});st.createIndex('dirty','dirty',{unique:false})}if(!db.objectStoreNames.contains('revisions')){const st=db.createObjectStore('revisions',{keyPath:'id'});st.createIndex('pageKey','pageKey',{unique:false});st.createIndex('at','at',{unique:false})}if(!db.objectStoreNames.contains('assets')){const st=db.createObjectStore('assets',{keyPath:'id'});st.createIndex('dirty','dirty',{unique:false});st.createIndex('createdAt','createdAt',{unique:false})}};r.onsuccess=()=>{const db=r.result;db.onversionchange=()=>{db.close();noteDbPromise=null};res(db)};r.onerror=()=>{noteDbPromise=null;rej(r.error)}});return noteDbPromise
}
async function noteGet(store,key){const db=await noteDb();return new Promise((res,rej)=>{const r=db.transaction(store,'readonly').objectStore(store).get(key);r.onsuccess=()=>res(r.result||null);r.onerror=()=>rej(r.error)})}
async function notePut(store,value){const db=await noteDb();return new Promise((res,rej)=>{const tx=db.transaction(store,'readwrite');tx.objectStore(store).put(value);tx.oncomplete=()=>res(value);tx.onerror=()=>rej(tx.error)})}
async function noteDelete(store,key){const db=await noteDb();return new Promise((res,rej)=>{const tx=db.transaction(store,'readwrite');tx.objectStore(store).delete(key);tx.oncomplete=()=>res();tx.onerror=()=>rej(tx.error)})}
async function noteAll(store='pages'){const db=await noteDb();return new Promise((res,rej)=>{const r=db.transaction(store,'readonly').objectStore(store).getAll();r.onsuccess=()=>res(r.result||[]);r.onerror=()=>rej(r.error)})}
async function noteAllIndex(store,indexName,key){const db=await noteDb();return new Promise((res,rej)=>{const st=db.transaction(store,'readonly').objectStore(store),idx=st.index(indexName),r=idx.getAll(IDBKeyRange.only(key));r.onsuccess=()=>res(r.result||[]);r.onerror=()=>rej(r.error)})}
function pageKey(course,date,pageId){return `${course}::${date}::${pageId}`}
function makePage(course=drawCourse,date=drawDate,index=0,{dirty=false}={}){const id=`p${Date.now().toString(36)}${Math.random().toString(36).slice(2,7)}`;return{schema:3,key:pageKey(course,date,id),courseKey:course,dateKey:date,pageId:id,order:index,paper:'ruled',width:CANVAS_W,height:CANVAS_H,strokes:[],images:[],attachments:[],rev:0,cloudRev:0,dirty:!!dirty,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}}
async function pagesFor(course,date){return (await noteAllIndex('pages','courseDate',[course,date])).sort((a,b)=>(Number(a.order)||0)-(Number(b.order)||0)||String(a.createdAt).localeCompare(String(b.createdAt)))}
function pageHasContent(p){return !!((p?.strokes||[]).length||(p?.images||[]).length||(p?.attachments||[]).length||Number(p?._strokeCount)>0||Number(p?._itemCount)>0||Number(p?.rev)>0||p?.conflictCopy)}
function compactPageMemory(p){if(!p)return p;const n=(p.strokes||[]).length,m=(p.images||[]).length+(p.attachments||[]).length;return{...p,strokes:[],images:p.images||[],attachments:p.attachments||[],_unloaded:true,_strokeCount:n,_itemCount:m}}
async function ensurePages(){
  let full=await pagesFor(drawCourse,drawDate);
  if(!full.length){const p=makePage(drawCourse,drawDate,0,{dirty:false});await notePut('pages',p);full=[p]}
  activePageIndex=Math.max(0,Math.min(activePageIndex,full.length-1));activePage=structuredClone(full[activePageIndex]);
  drawPages=full.map((p,i)=>i===activePageIndex?structuredClone(p):compactPageMemory(p));
  activePageChanged=false;undoStack=[];redoStack=[];
  renderInfiniteNotebook();
}
function noteStatus(text,kind=''){const el=$('#drawingSaveState');if(el){el.textContent=text;el.className=`save-state ${kind}`.trim()}}
function canvasPoint(e,c){const r=c.getBoundingClientRect();return{x:(e.clientX-r.left)*c.width/r.width,y:(e.clientY-r.top)*c.height/r.height,p:Number(e.pressure)||.5}}
function renderPaper(ctx,style){ctx.save();ctx.globalCompositeOperation='source-over';ctx.globalAlpha=1;ctx.fillStyle='#faf9f4';ctx.fillRect(0,0,CANVAS_W,CANVAS_H);ctx.strokeStyle='#dfe4e9';ctx.lineWidth=1;if(style==='ruled'){for(let y=120;y<CANVAS_H;y+=54){ctx.beginPath();ctx.moveTo(80,y);ctx.lineTo(CANVAS_W-60,y);ctx.stroke()}ctx.strokeStyle='#efc7c7';ctx.beginPath();ctx.moveTo(125,0);ctx.lineTo(125,CANVAS_H);ctx.stroke()}else if(style==='grid'){for(let x=0;x<CANVAS_W;x+=50){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,CANVAS_H);ctx.stroke()}for(let y=0;y<CANVAS_H;y+=50){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(CANVAS_W,y);ctx.stroke()}}ctx.restore()}
function drawStroke(ctx,s){const pts=s.points||[];if(!pts.length)return;ctx.save();ctx.lineCap='round';ctx.lineJoin='round';ctx.strokeStyle=s.color||'#11151d';ctx.globalAlpha=s.tool==='highlighter'?.26:s.tool==='pencil'?.72:1;ctx.globalCompositeOperation='source-over';ctx.lineWidth=(Number(s.width)||4)*(s.tool==='highlighter'?3:s.tool==='pencil'?.82:1);ctx.beginPath();ctx.moveTo(pts[0].x,pts[0].y);for(let i=1;i<pts.length;i++){const a=pts[i-1],b=pts[i],pressure=((a.p||.5)+(b.p||.5))/2;ctx.lineWidth=(Number(s.width)||4)*(s.tool==='highlighter'?3:s.tool==='pencil'?.82:1)*(s.tool==='highlighter'?1:Math.max(.7,Math.min(1.35,.65+pressure*.7)));ctx.lineTo(b.x,b.y)}if(pts.length===1)ctx.lineTo(pts[0].x+.01,pts[0].y+.01);ctx.stroke();ctx.restore()}
function cacheAssetBitmap(id,bitmap){if(assetBitmapCache.has(id)){const old=assetBitmapCache.get(id);if(old!==bitmap&&old?.close)try{old.close()}catch(_){}const oi=assetBitmapOrder.indexOf(id);if(oi>=0)assetBitmapOrder.splice(oi,1)}assetBitmapCache.set(id,bitmap);assetBitmapOrder.push(id);while(assetBitmapOrder.length>14){const drop=assetBitmapOrder.shift(),old=assetBitmapCache.get(drop);assetBitmapCache.delete(drop);if(old?.close)try{old.close()}catch(_){}}}
async function assetRenderable(id){if(!id)return null;if(assetBitmapCache.has(id))return assetBitmapCache.get(id);if(assetLoadPending.has(id))return null;assetLoadPending.add(id);try{const a=await noteGet('assets',id);if(!a?.blob)return null;let bmp=null;if('createImageBitmap'in window){try{bmp=await createImageBitmap(a.blob)}catch(_){}}if(!bmp){bmp=await new Promise((res,rej)=>{const img=new Image(),url=URL.createObjectURL(a.blob);img.onload=()=>{URL.revokeObjectURL(url);res(img)};img.onerror=()=>{URL.revokeObjectURL(url);rej(new Error('Image decode failed'))};img.src=url})}cacheAssetBitmap(id,bmp);return bmp}finally{assetLoadPending.delete(id)}}
function pageItems(page){return [...(page?.images||[]).map(x=>({...x,kind:'image'})),...(page?.attachments||[]).map(x=>({...x,kind:x.kind||'file'}))].sort((a,b)=>(Number(a.z)||0)-(Number(b.z)||0))}
function drawAttachmentCard(ctx,it){const x=Number(it.x)||120,y=Number(it.y)||120,w=Math.max(240,Number(it.w)||620),h=Math.max(120,Number(it.h)||170);ctx.save();ctx.fillStyle='#ffffff';ctx.strokeStyle='#d6d9df';ctx.lineWidth=3;ctx.beginPath();if(ctx.roundRect)ctx.roundRect(x,y,w,h,24);else ctx.rect(x,y,w,h);ctx.fill();ctx.stroke();ctx.fillStyle='#272b34';ctx.font='700 48px system-ui';ctx.fillText(it.type==='application/pdf'?'PDF':'FILE',x+34,y+68);ctx.fillStyle='#575d69';ctx.font='34px system-ui';const name=String(it.name||'Attachment');ctx.fillText(name.length>30?name.slice(0,29)+'…':name,x+34,y+122);ctx.restore()}
function drawItemSelection(ctx,it){if(!it||it.id!==selectedItemId)return;const x=Number(it.x)||0,y=Number(it.y)||0,w=Number(it.w)||0,h=Number(it.h)||0;ctx.save();ctx.strokeStyle='#596cff';ctx.lineWidth=5;ctx.setLineDash([14,10]);ctx.strokeRect(x,y,w,h);ctx.setLineDash([]);ctx.fillStyle='#596cff';for(const [hx,hy] of [[x,y],[x+w,y],[x,y+h],[x+w,y+h]]){ctx.beginPath();ctx.arc(hx,hy,18,0,Math.PI*2);ctx.fill()}ctx.restore()}
function requestAssetRerender(page,c){for(const it of page?.images||[]){if(!it.assetId||assetBitmapCache.has(it.assetId)||assetLoadPending.has(it.assetId))continue;assetRenderable(it.assetId).then(()=>{if(c?.isConnected){const hit=pageByKey(c.dataset.pageKey),p=hit?.index===activePageIndex&&activePage?.key===hit?.page?.key?activePage:hit?.page;if(p)drawPageToCanvas(p,c)}}).catch(e=>log('note-image-render-error',{assetId:it.assetId,error:String(e)}))}}
function drawPageToCanvas(page,c){if(!page||!c)return;const ctx=c.getContext('2d');renderPaper(ctx,page.paper||'ruled');for(const it of pageItems(page)){if(it.kind==='image'){const bmp=assetBitmapCache.get(it.assetId);if(bmp){ctx.save();const x=Number(it.x)||0,y=Number(it.y)||0,w=Math.max(20,Number(it.w)||500),h=Math.max(20,Number(it.h)||350),r=Number(it.rotation)||0;ctx.translate(x+w/2,y+h/2);ctx.rotate(r*Math.PI/180);ctx.globalAlpha=Number.isFinite(Number(it.opacity))?Number(it.opacity):1;ctx.drawImage(bmp,-w/2,-h/2,w,h);ctx.restore()}}else drawAttachmentCard(ctx,it);drawItemSelection(ctx,it)}for(const st of page.strokes||[])drawStroke(ctx,st);requestAssetRerender(page,c)}
function pageByKey(key){const i=drawPages.findIndex(p=>p.key===key);return i>=0?{page:drawPages[i],index:i}:null}
function setActivePageByKey(key){const hit=pageByKey(key);if(!hit)return false;activePageIndex=hit.index;activePage=structuredClone(hit.page);activePage.strokes=Array.isArray(activePage.strokes)?activePage.strokes:[];activePage.images=Array.isArray(activePage.images)?activePage.images:[];activePage.attachments=Array.isArray(activePage.attachments)?activePage.attachments:[];activePageChanged=false;selectedItemId='';itemGesture=null;undoStack=[];redoStack=[];const ps=$('#paperStyle');if(ps)ps.value=activePage.paper||'ruled';updateItemTools();return true}
function renderDrawing(){for(const c of $$('#infinitePaper canvas[data-page-key]')){const hit=pageByKey(c.dataset.pageKey);if(hit)drawPageToCanvas(hit.index===activePageIndex&&activePage?.key===hit.page.key?activePage:hit.page,c)}}
function pageUndoState(){return{strokes:structuredClone(activePage?.strokes||[]),images:structuredClone(activePage?.images||[]),attachments:structuredClone(activePage?.attachments||[])}}
function applyUndoState(v){if(!activePage)return;activePage.strokes=structuredClone(v?.strokes||Array.isArray(v)?v:[]);activePage.images=structuredClone(v?.images||[]);activePage.attachments=structuredClone(v?.attachments||[])}
function pushUndo(){undoStack.push(pageUndoState());if(undoStack.length>60)undoStack.shift();redoStack=[]}
function pointSegDist(p,a,b){const dx=b.x-a.x,dy=b.y-a.y;if(!dx&&!dy)return Math.hypot(p.x-a.x,p.y-a.y);const t=Math.max(0,Math.min(1,((p.x-a.x)*dx+(p.y-a.y)*dy)/(dx*dx+dy*dy)));return Math.hypot(p.x-(a.x+t*dx),p.y-(a.y+t*dy))}
function strokeHit(s,p,r){const pts=s.points||[];for(let i=0;i<pts.length;i++){if(Math.hypot(p.x-pts[i].x,p.y-pts[i].y)<=r)return true;if(i&&pointSegDist(p,pts[i-1],pts[i])<=r)return true}return false}
function activeCanvas(){if(!activePage)return null;return [...document.querySelectorAll('#infinitePaper canvas[data-page-key]')].find(c=>c.dataset.pageKey===activePage.key)||null}
function eraseAt(p){if(!activePage)return false;const before=activePage.strokes.length,r=22+drawWidth*2;activePage.strokes=activePage.strokes.filter(s=>!strokeHit(s,p,r));if(activePage.strokes.length!==before){activePageChanged=true;const c=activeCanvas();if(c)drawPageToCanvas(activePage,c);return true}return false}
async function checkpointPage(page){if(!page||!pageHasContent(page))return;const id=`${page.key}::r${page.rev}::${Date.now()}`;await notePut('revisions',{id,pageKey:page.key,at:Date.now(),page:structuredClone(page)});const all=(await noteAllIndex('revisions','pageKey',page.key)).sort((a,b)=>b.at-a.at);for(const old of all.slice(30))await noteDelete('revisions',old.id)}
async function saveActiveDrawing({checkpoint=false,cloud=true}={}){
  if(!activePage||!activePageChanged)return false;
  activePage.rev=(Number(activePage.rev)||0)+1;activePage.dirty=true;activePage.updatedAt=new Date().toISOString();await notePut('pages',activePage);drawPages[activePageIndex]=structuredClone(activePage);activePageChanged=false;
  const t=Date.now();if(checkpoint||t-lastCheckpointAt>15000){lastCheckpointAt=t;checkpointPage(activePage).catch(e=>log('note-checkpoint-error',{error:String(e)}))}
  noteStatus('Saved locally · cloud pending','dirty');if(cloud)scheduleNoteCloud(4500);renderDayChips().catch(()=>{});return true
}
function scheduleNoteCloud(ms=4500){clearTimeout(noteCloudTimer);noteCloudTimer=setTimeout(()=>flushDrawingCloud().catch(e=>{log('note-cloud-error',{error:String(e)});noteStatus('Saved locally · cloud pending','dirty')}),ms)}
function segmentHtml(p,i){return `<section class="paper-segment${p.conflictCopy?' conflict':''}" data-page-key="${esc(p.key)}" data-page-index="${i}"><div class="paper-segment-shell" data-canvas-host="${esc(p.key)}"><div class="paper-loading">${pageHasContent(p)?'Loading note…':'Keep scrolling to continue…'}</div></div></section>`}
async function mountSegment(el){
  if(!el||el.querySelector('canvas'))return;const key=el.dataset.pageKey,hit=pageByKey(key);if(!hit)return;const host=el.querySelector('[data-canvas-host]');if(!host)return;
  let page=hit.page;if(page._unloaded){const fresh=await noteGet('pages',key);if(!fresh)return;page=fresh;drawPages[hit.index]=fresh}
  const c=document.createElement('canvas');c.width=Number(page.width)||CANVAS_W;c.height=Number(page.height)||CANVAS_H;c.dataset.pageKey=key;c.className=[fingerDraw?'finger-draw':'',drawTool==='select'?'select-mode':''].filter(Boolean).join(' ');host.replaceChildren(c);drawPageToCanvas(activePage?.key===key?activePage:page,c);bindCanvas(c);
}
function unmountSegment(el){if(!el||drawing&&activePage?.key===el.dataset.pageKey)return;const c=el.querySelector('canvas');if(!c)return;const key=el.dataset.pageKey,hit=pageByKey(key);if(hit&&activePage?.key!==key&&!hit.page._unloaded)drawPages[hit.index]=compactPageMemory(hit.page);const host=el.querySelector('[data-canvas-host]');if(host)host.innerHTML='<div class="paper-loading">Scroll to load…</div>'}
function observeSegments(){
  segmentObserver?.disconnect();const root=$('#drawingViewport');if(!root||!('IntersectionObserver'in window)){for(const el of $$('.paper-segment'))mountSegment(el).catch(()=>{});return}
  segmentObserver=new IntersectionObserver(entries=>{for(const en of entries){if(en.isIntersecting)mountSegment(en.target).catch(e=>log('note-segment-load-error',{error:String(e)}));else if(Math.abs(en.boundingClientRect.top)>root.clientHeight*3)unmountSegment(en.target)}},{root,rootMargin:'1200px 0px 1200px 0px',threshold:0});
  for(const el of $$('.paper-segment'))segmentObserver.observe(el);
}
function renderInfiniteNotebook({preserveScroll=true}={}){
  const paper=$('#infinitePaper'),vp=$('#drawingViewport');if(!paper||!vp)return;const scroll=preserveScroll?vp.scrollTop:0;
  paper.innerHTML=drawPages.map(segmentHtml).join('');observeSegments();vp.scrollTop=scroll;const ps=$('#paperStyle');if(ps&&activePage)ps.value=activePage.paper||'ruled';
}
async function appendBlankSegment(){
  if(segmentGrowBusy)return null;segmentGrowBusy=true;
  try{
    const order=drawPages.length?Math.max(...drawPages.map(p=>Number(p.order)||0))+1:0,p=makePage(drawCourse,drawDate,order,{dirty:false});
    await notePut('pages',p);drawPages.push(p);
    const paper=$('#infinitePaper');if(paper){paper.insertAdjacentHTML('beforeend',segmentHtml(p,drawPages.length-1));const el=paper.lastElementChild;if(el){if(segmentObserver)segmentObserver.observe(el);else mountSegment(el).catch(()=>{})}}
    return p;
  }finally{segmentGrowBusy=false}
}
async function maybeGrowInfinitePaper(){
  const vp=$('#drawingViewport');if(!vp||segmentGrowBusy)return;
  // Keep a small paper buffer below the writer without re-rendering the whole notebook.
  if(vp.scrollHeight-vp.scrollTop-vp.clientHeight<1200)await appendBlankSegment();
}
async function switchDrawContext(course,date){if(activePageChanged)await saveActiveDrawing({checkpoint:true});drawCourse=course||'general';drawDate=date||localDateKey(new Date());activePageIndex=0;await ensurePages();loadNoteText();await renderDayChips();renderNotebookContext();noteStatus(drawPages.some(p=>p.dirty)?'Saved locally · cloud pending':'Local + OneDrive backup',drawPages.some(p=>p.dirty)?'dirty':'');const vp=$('#drawingViewport');if(vp)vp.scrollTop=0}
function renderNotebookContext(){const opt=[...$('#notesCourse').options].find(o=>o.value===drawCourse),name=opt?.textContent||drawCourse;$('#notebookContext').textContent=`${name} · ${fmtDate(`${drawDate}T12:00:00`,{weekday:'short',month:'short',day:'numeric'})}`}
async function renderDayChips(){const pages=(await noteAll('pages')).filter(p=>p.courseKey===drawCourse),daysWithInk=new Set();for(const p of pages){if(pageHasContent(p))daysWithInk.add(p.dateKey)}const keys=[...new Set([drawDate,localDateKey(new Date()),...daysWithInk])].sort().reverse();$('#noteDayChips').innerHTML=keys.map(k=>{const today=k===localDateKey(new Date()),label=today?'Today':fmtDate(`${k}T12:00:00`,{weekday:'short',month:'short',day:'numeric'});return `<button class="note-day-chip ${k===drawDate?'active':''}" data-note-date="${k}">${esc(label)}${daysWithInk.has(k)?'<span class="ink-dot" aria-label="has notes">●</span>':''}</button>`}).join('')}
async function renderNotes(){const sel=$('#notesCourse'),opts=courseOptions(),sig=JSON.stringify(opts);if(sel.dataset.signature!==sig){sel.innerHTML=opts.map(([id,n])=>`<option value="${esc(id)}">${esc(n)}</option>`).join('');sel.dataset.signature=sig}if(!drawCourse||!opts.some(([id])=>id===drawCourse))drawCourse=sel.value||opts[0]?.[0]||'general';sel.value=drawCourse;$('#notesDate').value=drawDate;if(!activePage||activePage.courseKey!==drawCourse||activePage.dateKey!==drawDate)await ensurePages();else renderInfiniteNotebook();await renderDayChips();renderNotebookContext();loadNoteText();noteStatus(drawPages.some(p=>p.dirty)?'Saved locally · cloud pending':'Local + OneDrive backup',drawPages.some(p=>p.dirty)?'dirty':'')}
function loadNoteText(){const k=drawCourse,d=drawDate,book=state.study?.noteBooks?.[k]||{},entry=book[d]||{};$('#notesText').value=entry.text||'';$('#notesState').textContent='Synced copy'}
function mergeNoteBooks(local,remote){const out=structuredClone(local&&typeof local==='object'?local:{});for(const[course,days]of Object.entries(remote||{})){out[course]=out[course]||{};for(const[day,re]of Object.entries(days||{})){const le=out[course][day];if(!le){out[course][day]=structuredClone(re);continue}const lt=Date.parse(le.updatedAt||0)||0,rt=Date.parse(re.updatedAt||0)||0,newer=rt>lt?re:le,older=rt>lt?le:re,seen=new Map();for(const p of [...(older.pages||[]),...(newer.pages||[])]){const k=typeof p==='string'?`s:${p}`:`o:${JSON.stringify(p)}`;if(!seen.has(k))seen.set(k,structuredClone(p))}out[course][day]={...structuredClone(older),...structuredClone(newer),text:String(newer.text??older.text??''),pages:[...seen.values()],updatedAt:newer.updatedAt||older.updatedAt||null}}}return out}
function saveNote(){const k=drawCourse,d=drawDate;if(!k||!d)return;state.study=state.study||{};state.study.noteBooks=state.study.noteBooks||{};const book={...(state.study.noteBooks[k]||{})},prev=book[d]||{text:'',pages:[]};book[d]={...prev,text:$('#notesText').value,pages:Array.isArray(prev.pages)?prev.pages:[],updatedAt:new Date().toISOString()};state.study.noteBooks[k]=book;markClock('study.noteBooks');saveLocalCloud();$('#notesState').textContent='Saved locally · syncing…';schedulePush(300)}


function safeAssetExt(type,name=''){const byName=String(name).match(/\.([A-Za-z0-9]{1,8})$/)?.[1]?.toLowerCase();if(byName)return byName;return({'image/png':'png','image/jpeg':'jpg','image/webp':'webp','image/gif':'gif','application/pdf':'pdf'})[type]||'bin'}
function assetCloudName(a){return a.cloudName||`wha2.${a.id}.${safeAssetExt(a.type,a.name)}`}
function currentVisiblePageKey(){const vp=$('#drawingViewport'),els=$$('.paper-segment');if(!vp||!els.length)return activePage?.key||drawPages[0]?.key||'';const vr=vp.getBoundingClientRect(),mid=(vr.top+vr.bottom)/2;let best=null,dist=Infinity;for(const el of els){const r=el.getBoundingClientRect(),cy=(r.top+r.bottom)/2,d=Math.abs(cy-mid);if(d<dist){dist=d;best=el}}return best?.dataset.pageKey||activePage?.key||''}
function activateVisibleSegment(){const key=currentVisiblePageKey();if(key&&activePage?.key!==key)setActivePageByKey(key);return activePage}
async function normalizedImageBlob(file){let bmp=null;try{bmp=await createImageBitmap(file)}catch(_){return{blob:file,width:1600,height:1200,type:file.type||'image/*'}}const ow=bmp.width||1600,oh=bmp.height||1200,max=2600,scale=Math.min(1,max/Math.max(ow,oh));if(scale===1&&file.size<=6*1024*1024)return{blob:file,width:ow,height:oh,type:file.type||'image/*'};const w=Math.max(1,Math.round(ow*scale)),h=Math.max(1,Math.round(oh*scale)),c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(bmp,0,0,w,h);if(bmp.close)try{bmp.close()}catch(_){}const outType=file.type==='image/png'?'image/png':'image/jpeg',quality=outType==='image/png'?undefined:.91;const blob=await new Promise(res=>c.toBlob(res,outType,quality));return{blob:blob||file,width:w,height:h,type:(blob||file).type||outType}}
async function createAssetFromFile(file,{source='picker'}={}){const id=`a${Date.now().toString(36)}${Math.random().toString(36).slice(2,9)}`;let blob=file,width=0,height=0,type=file.type||'application/octet-stream';if(type.startsWith('image/')){const n=await normalizedImageBlob(file);blob=n.blob;width=n.width;height=n.height;type=n.type}const asset={id,blob,name:file.name||`${source}-${id}`,type,size:blob.size,source,width,height,createdAt:new Date().toISOString(),dirty:true,cloudBackedAt:null};asset.cloudName=assetCloudName(asset);await notePut('assets',asset);return asset}
function defaultInsertRect(asset,ordinal=0){const maxW=CANVAS_W*.72,maxH=CANVAS_H*.56,iw=Number(asset.width)||900,ih=Number(asset.height)||650,scale=Math.min(1,maxW/iw,maxH/ih),w=Math.max(260,iw*scale),h=Math.max(180,ih*scale);return{x:Math.max(60,(CANVAS_W-w)/2+ordinal*28),y:180+ordinal*34,w,h}}
function updateItemTools(){const del=$('#deleteItemBtn'),fit=$('#fitItemBtn'),open=$('#openItemBtn');if(del)del.disabled=!selectedItemId;if(fit)fit.disabled=!selectedItemId;if(open)open.disabled=!selectedItemId}
async function insertFiles(files,{source='picker'}={}){const arr=[...files].filter(Boolean);if(!arr.length)return;activateVisibleSegment();if(!activePage)return;pushUndo();let ordinal=0;for(const f of arr){const asset=await createAssetFromFile(f,{source}),r=defaultInsertRect(asset,ordinal++),z=Date.now()+ordinal;if(asset.type.startsWith('image/')){activePage.images=activePage.images||[];const it={id:`i${asset.id}`,assetId:asset.id,name:asset.name,type:asset.type,...r,rotation:0,opacity:1,z};activePage.images.push(it);selectedItemId=it.id;assetRenderable(asset.id).then(()=>{const c=activeCanvas();if(c)drawPageToCanvas(activePage,c)}).catch(()=>{})}else{activePage.attachments=activePage.attachments||[];const it={id:`f${asset.id}`,assetId:asset.id,name:asset.name,type:asset.type,x:120,y:190+ordinal*34,w:CANVAS_W-240,h:170,z};activePage.attachments.push(it);selectedItemId=it.id}}activePageChanged=true;const c=activeCanvas();if(c)drawPageToCanvas(activePage,c);updateItemTools();await saveActiveDrawing({checkpoint:true,cloud:false});noteStatus(`${arr.length} item${arr.length===1?'':'s'} saved locally · cloud pending`,'dirty');scheduleNoteCloud(900);closeInsertSheet()}
function openInsertSheet(){const s=$('#insertSheet');if(s){s.hidden=false;requestAnimationFrame(()=>s.classList.add('open'))}}
function closeInsertSheet(){const s=$('#insertSheet');if(!s)return;s.classList.remove('open');setTimeout(()=>{if(!s.classList.contains('open'))s.hidden=true},180)}
async function pasteFromClipboard(){try{if(!navigator.clipboard?.read)throw new Error('Clipboard image paste is not supported here');const items=await navigator.clipboard.read(),files=[];for(const item of items){for(const type of item.types||[]){if(type.startsWith('image/')){const b=await item.getType(type);files.push(new File([b],`pasted-${Date.now()}.${safeAssetExt(type)}`,{type}));break}}}if(!files.length)throw new Error('No image found in clipboard');await insertFiles(files,{source:'clipboard'})}catch(e){noteStatus(`${String(e.message||e)} · use Photos`, 'error')}}
function notebookItemAt(p){if(!activePage)return null;const items=pageItems(activePage).slice().reverse();for(const it of items){const x=Number(it.x)||0,y=Number(it.y)||0,w=Number(it.w)||0,h=Number(it.h)||0;if(p.x>=x&&p.x<=x+w&&p.y>=y&&p.y<=y+h)return it}return null}
function findActiveItem(id=selectedItemId){if(!activePage||!id)return null;return (activePage.images||[]).find(x=>x.id===id)||(activePage.attachments||[]).find(x=>x.id===id)||null}
function beginItemGesture(p,item){selectedItemId=item?.id||'';updateItemTools();if(!item){itemGesture=null;const c=activeCanvas();if(c)drawPageToCanvas(activePage,c);return}pushUndo();const hr=54,nearResize=Math.hypot(p.x-(item.x+item.w),p.y-(item.y+item.h))<hr;itemGesture={id:item.id,mode:nearResize?'resize':'move',sx:p.x,sy:p.y,x:item.x,y:item.y,w:item.w,h:item.h};const c=activeCanvas();if(c)drawPageToCanvas(activePage,c)}
function moveItemGesture(p){if(!itemGesture)return;const it=findActiveItem(itemGesture.id);if(!it)return;const dx=p.x-itemGesture.sx,dy=p.y-itemGesture.sy;if(itemGesture.mode==='resize'){const ratio=Math.max(.1,itemGesture.w/Math.max(1,itemGesture.h)),nw=Math.max(140,itemGesture.w+dx),nh=Math.max(100,itemGesture.h+dy);if(it.type?.startsWith('image/')){if(Math.abs(dx)>Math.abs(dy))it.w=nw,it.h=nw/ratio;else it.h=nh,it.w=nh*ratio}else{it.w=nw;it.h=nh}}else{it.x=Math.max(-it.w*.7,Math.min(CANVAS_W-it.w*.3,itemGesture.x+dx));it.y=Math.max(-it.h*.7,Math.min(CANVAS_H-it.h*.3,itemGesture.y+dy))}activePageChanged=true;const c=activeCanvas();if(c)drawPageToCanvas(activePage,c)}
async function endItemGesture(){if(!itemGesture)return;itemGesture=null;if(activePageChanged)await saveActiveDrawing({checkpoint:false})}
async function deleteSelectedItem(){if(!activePage||!selectedItemId)return;pushUndo();const id=selectedItemId;activePage.images=(activePage.images||[]).filter(x=>x.id!==id);activePage.attachments=(activePage.attachments||[]).filter(x=>x.id!==id);selectedItemId='';activePageChanged=true;const c=activeCanvas();if(c)drawPageToCanvas(activePage,c);updateItemTools();await saveActiveDrawing({checkpoint:true})}
async function fitSelectedItem(){const it=findActiveItem();if(!it)return;pushUndo();const ratio=Math.max(.1,(Number(it.w)||1)/(Number(it.h)||1));it.w=CANVAS_W-120;it.h=it.w/ratio;if(it.h>CANVAS_H-120){it.h=CANVAS_H-120;it.w=it.h*ratio}it.x=(CANVAS_W-it.w)/2;it.y=60;activePageChanged=true;const c=activeCanvas();if(c)drawPageToCanvas(activePage,c);await saveActiveDrawing({checkpoint:false})}
async function openSelectedItem(){const it=findActiveItem();if(!it)return;const popup=window.open('about:blank','_blank');const a=await noteGet('assets',it.assetId);if(!a?.blob){try{popup?.close()}catch(_){}return}const url=URL.createObjectURL(a.blob);if(popup)popup.location.href=url;else location.href=url;setTimeout(()=>URL.revokeObjectURL(url),60000)}

function emergencyDrawingSnapshot(){
  if(!activePage||!activePageChanged)return;const draft={...structuredClone(activePage),dirty:true,updatedAt:new Date().toISOString()};notePut('pages',draft).catch(e=>log('note-emergency-save-error',{error:String(e)}));lastStrokeSafetySaveAt=Date.now();
}
function bindCanvas(c){
  c.addEventListener('pointerdown',e=>{
    if(activePage?.key!==c.dataset.pageKey)setActivePageByKey(c.dataset.pageKey);const p=canvasPoint(e,c);
    if(drawTool==='select'){
      e.preventDefault();drawing=true;c.setPointerCapture?.(e.pointerId);beginItemGesture(p,notebookItemAt(p));return;
    }
    const canDraw=e.pointerType==='pen'||e.pointerType==='mouse'||fingerDraw;if(!canDraw)return;if(e.pointerType==='pen'||fingerDraw)e.preventDefault();drawing=true;c.setPointerCapture?.(e.pointerId);pushUndo();activePageChanged=true;lastStrokeSafetySaveAt=Date.now();if(drawTool==='eraser'){eraseAt(p);liveStroke=null}else{liveStroke={id:`s${Date.now().toString(36)}${Math.random().toString(36).slice(2,6)}`,tool:drawTool,color:drawColor,width:drawWidth,points:[p]};activePage.strokes.push(liveStroke);drawPageToCanvas(activePage,c)}});
  c.addEventListener('pointermove',e=>{
    if(!drawing||!activePage||activePage.key!==c.dataset.pageKey)return;const events=typeof e.getCoalescedEvents==='function'?(e.getCoalescedEvents().length?e.getCoalescedEvents():[e]):[e];
    if(drawTool==='select'){e.preventDefault();moveItemGesture(canvasPoint(events.at(-1)||e,c));return}
    if(e.pointerType==='pen'||fingerDraw)e.preventDefault();for(const ev of events){const p=canvasPoint(ev,c);if(drawTool==='eraser'){eraseAt(p)}else if(liveStroke){const last=liveStroke.points[liveStroke.points.length-1];if(Math.hypot(p.x-last.x,p.y-last.y)>1.0){liveStroke.points.push(p);activePageChanged=true;const ctx=c.getContext('2d');drawStroke(ctx,{...liveStroke,points:[last,p]})}}}if(activePageChanged&&Date.now()-lastStrokeSafetySaveAt>5000)emergencyDrawingSnapshot()});
  const end=async e=>{if(!drawing||activePage?.key!==c.dataset.pageKey)return;drawing=false;try{c.releasePointerCapture?.(e.pointerId)}catch(_){}if(drawTool==='select'){await endItemGesture();return}liveStroke=null;await saveActiveDrawing({checkpoint:false});maybeGrowInfinitePaper().catch(()=>{})};c.addEventListener('pointerup',end);c.addEventListener('pointercancel',end);
  c.addEventListener('dblclick',e=>{if(drawTool!=='select')return;if(activePage?.key!==c.dataset.pageKey)setActivePageByKey(c.dataset.pageKey);const it=notebookItemAt(canvasPoint(e,c));if(it){selectedItemId=it.id;updateItemTools();openSelectedItem().catch(()=>{})}})
}
function bindDrawing(){const vp=$('#drawingViewport');vp?.addEventListener('scroll',()=>maybeGrowInfinitePaper().catch(()=>{}),{passive:true});renderInfiniteNotebook()}
function undoDrawing(){if(!activePage||!undoStack.length)return;redoStack.push(pageUndoState());applyUndoState(undoStack.pop());selectedItemId='';activePageChanged=true;const c=activeCanvas();if(c)drawPageToCanvas(activePage,c);updateItemTools();saveActiveDrawing({checkpoint:false})}
function redoDrawing(){if(!activePage||!redoStack.length)return;undoStack.push(pageUndoState());applyUndoState(redoStack.pop());selectedItemId='';activePageChanged=true;const c=activeCanvas();if(c)drawPageToCanvas(activePage,c);updateItemTools();saveActiveDrawing({checkpoint:false})}

function b64Text(s){const bytes=new TextEncoder().encode(String(s));let bin='';for(const b of bytes)bin+=String.fromCharCode(b);return btoa(bin).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function noteFileName(p){return `whn2.${b64Text(p.courseKey)}.${p.dateKey}.${p.pageId}.r${p.rev}.${Date.now()}.json`}
function graphPath(parts){return parts.filter(Boolean).map(x=>encodeURIComponent(x)).join('/')}
function notesFolderParts(){return [...String(cfg.folder||'').split('/').filter(Boolean),NOTES_FOLDER]}
async function ensureNotesFolder(){const parts=String(cfg.folder||'').split('/').filter(Boolean),parent=`/me/drive/root:/${graphPath(parts)}:/children`,target=`/me/drive/root:/${graphPath([...parts,NOTES_FOLDER])}`;let r=await graph(target);if(r.ok)return; if(r.status!==404)throw new Error(`Notes folder check failed (${r.status})`);r=await graph(parent,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:NOTES_FOLDER,folder:{},'@microsoft.graph.conflictBehavior':'fail'})});if(!r.ok&&r.status!==409)throw new Error(`Could not create notes backup folder (${r.status})`)}
async function ensureNotesAssetsFolder(){await ensureNotesFolder();const parent=`/me/drive/root:/${graphPath(notesFolderParts())}:/children`,target=`/me/drive/root:/${graphPath([...notesFolderParts(),NOTES_ASSETS_FOLDER])}`;let r=await graph(target);if(r.ok)return;if(r.status!==404)throw new Error(`Notes asset folder check failed (${r.status})`);r=await graph(parent,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:NOTES_ASSETS_FOLDER,folder:{},'@microsoft.graph.conflictBehavior':'fail'})});if(!r.ok&&r.status!==409)throw new Error(`Could not create note assets folder (${r.status})`)}
async function uploadAsset(a){if(!a?.blob)return;await ensureNotesAssetsFolder();const name=assetCloudName(a),path=`/me/drive/root:/${graphPath([...notesFolderParts(),NOTES_ASSETS_FOLDER,name])}:/content`;const r=await graph(path,{method:'PUT',headers:{'Content-Type':a.type||'application/octet-stream'},body:a.blob});if(!r.ok)throw new Error(`Attachment backup failed (${r.status})`);const latest=await noteGet('assets',a.id);if(latest){latest.dirty=false;latest.cloudBackedAt=new Date().toISOString();latest.cloudName=name;await notePut('assets',latest)}}
async function uploadPageSnapshot(p){await ensureNotesFolder();const path=`/me/drive/root:/${graphPath([...notesFolderParts(),noteFileName(p)])}:/content`;const payload={schema:3,type:'warrior-drawing-page',appVersion:APP_VERSION,deviceId:meta.deviceId,exportedAt:new Date().toISOString(),page:p};const r=await graph(path,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!r.ok)throw new Error(`Drawing backup failed (${r.status})`)}
async function flushDrawingCloud(){const token=await accessToken();if(!token)return false;const assets=(await noteAll('assets')).filter(a=>a.dirty),pages=(await noteAll('pages')).filter(p=>p.dirty);if(!assets.length&&!pages.length){if(activePage)noteStatus('Local + OneDrive backup');return true}noteStatus(`Backing up ${assets.length?`${assets.length} media · `:''}${pages.length} note section${pages.length===1?'':'s'}…`,'dirty');for(const a of assets)await uploadAsset(a);for(const p of pages){await uploadPageSnapshot(p);const latest=await noteGet('pages',p.key);if(latest&&Number(latest.rev)===Number(p.rev)){latest.dirty=false;latest.cloudRev=latest.rev;latest.cloudBackedAt=new Date().toISOString();await notePut('pages',latest);if(activePage?.key===latest.key){activePage=structuredClone(latest);activePageChanged=false}const di=drawPages.findIndex(x=>x.key===latest.key);if(di>=0)drawPages[di]=structuredClone(latest)}}noteStatus('Local + OneDrive backup');$('#noteSafetyStatus').textContent=`Last notebook backup: ${new Date().toLocaleTimeString()} · ${assets.length} media`;return true}
async function listCloudNoteFiles(){await ensureNotesFolder();let url=`/me/drive/root:/${graphPath(notesFolderParts())}:/children?$top=200&$select=id,name,size,lastModifiedDateTime`,out=[];while(url){const r=await graph(url);if(!r.ok)throw new Error(`Note backup list failed (${r.status})`);const j=await r.json();out.push(...(j.value||[]));url=j['@odata.nextLink']||''}return out.filter(x=>/^whn2\./.test(x.name||''))}
async function ensurePageAssetsLocal(page){const items=[...(page?.images||[]),...(page?.attachments||[])];for(const it of items){if(!it?.assetId)continue;const has=await noteGet('assets',it.assetId);if(has?.blob)continue;const name=`wha2.${it.assetId}.${safeAssetExt(it.type,it.name)}`,path=`/me/drive/root:/${graphPath([...notesFolderParts(),NOTES_ASSETS_FOLDER,name])}:/content`;const r=await graph(path);if(!r.ok){log('note-asset-restore-missing',{assetId:it.assetId,status:r.status});continue}const blob=await r.blob();await notePut('assets',{id:it.assetId,blob,name:it.name||name,type:it.type||blob.type||'application/octet-stream',size:blob.size,cloudName:name,createdAt:new Date().toISOString(),dirty:false,cloudBackedAt:new Date().toISOString()})}}
async function fetchGraphDownload(id){const r=await graph(`/me/drive/items/${encodeURIComponent(id)}/content`);if(!r.ok)throw new Error(`Note restore failed (${r.status})`);return r.json()}
async function restoreCloudNotes(){noteStatus('Checking OneDrive note revisions…','dirty');await flushDrawingCloud().catch(()=>{});const files=await listCloudNoteFiles(),latest=new Map();for(const f of files){const m=String(f.name).match(/^whn2\.([^.]+)\.(\d{4}-\d{2}-\d{2})\.([^.]+)\.r(\d+)\.(\d+)\.json$/);if(!m)continue;const k=`${m[1]}|${m[2]}|${m[3]}`,rev=Number(m[4])||0,stamp=Number(m[5])||0,prev=latest.get(k);if(!prev||rev>prev.rev||(rev===prev.rev&&stamp>prev.stamp))latest.set(k,{rev,stamp,file:f})}let imported=0,conflicts=0;for(const {file} of latest.values()){const snap=await fetchGraphDownload(file.id),rp=snap?.page;if(!rp?.key||!Array.isArray(rp.strokes))continue;await ensurePageAssetsLocal(rp);const lp=await noteGet('pages',rp.key);if(!lp){rp.dirty=false;rp.cloudRev=rp.rev;await notePut('pages',rp);imported++;continue}const remoteNew=(Number(rp.rev)||0)>(Number(lp.cloudRev)||0)||Date.parse(rp.updatedAt||0)>Date.parse(lp.updatedAt||0);if(!remoteNew)continue;if(lp.dirty&&JSON.stringify({s:lp.strokes||[],i:lp.images||[],a:lp.attachments||[]})!==JSON.stringify({s:rp.strokes||[],i:rp.images||[],a:rp.attachments||[]})){const cp=structuredClone(rp),newId=`${rp.pageId}c${Date.now().toString(36).slice(-4)}`;cp.pageId=newId;cp.key=pageKey(cp.courseKey,cp.dateKey,newId);cp.order=(Number(lp.order)||0)+.5;cp.dirty=false;cp.cloudRev=cp.rev;cp.conflictCopy=true;await notePut('pages',cp);conflicts++}else{rp.dirty=false;rp.cloudRev=rp.rev;await notePut('pages',rp);imported++}}await switchDrawContext(drawCourse,drawDate);$('#noteSafetyStatus').textContent=`OneDrive restore complete · ${imported} updated · ${conflicts} conflict copies preserved`;noteStatus('Local + OneDrive backup');return{imported,conflicts}}
function blobToDataUrl(blob){return new Promise((res,rej)=>{const fr=new FileReader();fr.onload=()=>res(fr.result);fr.onerror=()=>rej(fr.error);fr.readAsDataURL(blob)})}
function dataUrlToBlob(s){const [h,b]=String(s).split(','),m=String(h).match(/data:([^;]+)/),bin=atob(b||''),u=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)u[i]=bin.charCodeAt(i);return new Blob([u],{type:m?.[1]||'application/octet-stream'})}
async function exportNotesBackup(){const pages=await noteAll('pages'),revisions=await noteAll('revisions'),assets0=await noteAll('assets'),assets=[];for(const a0 of assets0){const a={...a0};if(a.blob){a.dataUrl=await blobToDataUrl(a.blob);delete a.blob}assets.push(a)}const payload={format:'Warrior Hub Mobile notebook backup',schema:3,version:APP_VERSION,exportedAt:new Date().toISOString(),pages,revisions,assets};const blob=new Blob([JSON.stringify(payload)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`warrior-notebook-backup-${localDateKey(new Date())}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1200)}
async function importNotesBackup(file){const j=JSON.parse(await file.text());if(![2,3].includes(Number(j.schema))||!Array.isArray(j.pages))throw new Error('Unsupported notes backup');let assetCount=0;for(const a0 of j.assets||[]){if(!a0?.id||!a0.dataUrl)continue;const old=await noteGet('assets',a0.id);if(old?.blob)continue;const a={...a0,blob:dataUrlToBlob(a0.dataUrl),dirty:true};delete a.dataUrl;a.size=a.blob.size;await notePut('assets',a);assetCount++}let count=0;for(const rp0 of j.pages){const rp=structuredClone(rp0);if(!rp?.key||!Array.isArray(rp.strokes))continue;rp.images=Array.isArray(rp.images)?rp.images:[];rp.attachments=Array.isArray(rp.attachments)?rp.attachments:[];const lp=await noteGet('pages',rp.key);if(lp&&lp.dirty&&JSON.stringify({s:lp.strokes,i:lp.images,a:lp.attachments})!==JSON.stringify({s:rp.strokes,i:rp.images,a:rp.attachments})){const id=`${rp.pageId}i${Date.now().toString(36).slice(-4)}`;rp.pageId=id;rp.key=pageKey(rp.courseKey,rp.dateKey,id);rp.order=(Number(lp.order)||0)+.4}rp.dirty=true;await notePut('pages',rp);count++}await switchDrawContext(drawCourse,drawDate);scheduleNoteCloud(600);$('#noteSafetyStatus').textContent=`Imported ${count} note sections + ${assetCount} media · local originals were not deleted`}

function renderSetup(){cfg=loadJson(CFG_KEY,cfg);$('#clientIdInput').value=cfg.clientId||DEFAULT_MS_CLIENT_ID;$('#folderInput').value=cfg.folder||'WARRIOR HUB';$('#tenantInput').value=cfg.tenant||'common';$('#redirectUriText').textContent=redirectUri();getAccount().then(a=>$('#accountInfo').textContent=a?`Signed in: ${a.displayName||a.userPrincipalName||'Microsoft account'}`:'Not signed in').catch(()=>{});Promise.all([noteAll('pages'),noteAll('revisions'),noteAll('assets')]).then(([p,r,a])=>$('#noteSafetyStatus').textContent=`Local notebook: ${p.filter(pageHasContent).length} written sections · ${a.length} media · ${r.length} recovery checkpoints`).catch(()=>{})}

function timerRemaining(){return timer.running?Math.max(0,timer.endAt-Date.now()):Math.max(0,timer.remainingMs||0)}
function renderTimer(){const live=remoteIsFresh();if(live){const s=remoteLive.study||{},el=$('#timerText'),btn=$('#timerToggle');if(el)el.textContent=remoteTime(remoteRemaining());if(btn)btn.textContent=s.running?'Pause':'Start';return}const r=timerRemaining(),s=Math.ceil(r/1000),m=Math.floor(s/60),ss=s%60;const el=$('#timerText'),btn=$('#timerToggle');if(el)el.textContent=`${String(m).padStart(2,'0')}:${String(ss).padStart(2,'0')}`;if(btn)btn.textContent=timer.running?'Pause':'Start';if(timer.running&&r<=0){timer={remainingMs:10*60*1000,running:false,endAt:0};saveJson(TIMER_KEY,timer)}}
function startTimerLoop(){clearInterval(timerHandle);timerHandle=setInterval(()=>{if(currentView==='today')renderTimer();if(currentView==='study')renderRemoteStudy()},500)}
function toggleTimer(){if(remoteIsFresh()){sendRemoteCommand(`study.${remoteLive.study?.running?'pause':'start'}`).catch(()=>{});return}if(timer.running){timer.remainingMs=timerRemaining();timer.running=false;timer.endAt=0}else{timer.running=true;timer.endAt=Date.now()+Math.max(1000,timer.remainingMs||50*60*1000)}saveJson(TIMER_KEY,timer);renderTimer()}
function resetTimer(){if(remoteIsFresh()){sendRemoteCommand('study.reset').catch(()=>{});return}timer={remainingMs:50*60*1000,running:false,endAt:0};saveJson(TIMER_KEY,timer);renderTimer()}

function trackedPaths(s={}){const out=[];for(const key of Object.keys(s||{})){if(key==='sync')continue;if(['study','settings','previewRead'].includes(key)&&s[key]&&typeof s[key]==='object'&&!Array.isArray(s[key]))for(const sk of Object.keys(s[key]))out.push(`${key}.${sk}`);else out.push(key)}return out}
function getPath(o,p){return p.split('.').reduce((v,k)=>v==null?undefined:v[k],o)}
function setPath(o,p,v){const ps=p.split('.');let c=o;for(let i=0;i<ps.length-1;i++){if(!c[ps[i]]||typeof c[ps[i]]!=='object'||Array.isArray(c[ps[i]]))c[ps[i]]={};c=c[ps[i]]}c[ps.at(-1)]=structuredClone(v)}
function markClock(path){meta.clocks=meta.clocks||{};meta.clocks[path]=Date.now();saveJson(META_KEY,meta)}
function merge(local,remote,localClocks,remoteClocks,remoteUpdated){const out=structuredClone(local||{}),paths=new Set([...trackedPaths(local||{}),...trackedPaths(remote||{}),...Object.keys(localClocks||{}),...Object.keys(remoteClocks||{})]),clocks={...(remoteClocks||{}),...(localClocks||{})};for(const p of paths){const lv=getPath(local,p),rv=getPath(remote,p);if(typeof rv==='undefined')continue;if(typeof lv==='undefined'){setPath(out,p,rv);clocks[p]=Number(remoteClocks?.[p]||remoteUpdated||0);continue}if(p==='study.noteBooks'){setPath(out,p,mergeNoteBooks(lv,rv));clocks[p]=Math.max(Number(localClocks?.[p]||0),Number(remoteClocks?.[p]||0),Number(remoteUpdated||0));continue}const lc=Number(localClocks?.[p]||0),rc=Number(remoteClocks?.[p]||0);if(rc>lc)setPath(out,p,rv);clocks[p]=Math.max(lc,rc)}return{state:out,clocks}}
function saveLocalCloud(){cloud=cloud||{schema:SCHEMA,app:'Warrior Hub',version:APP_VERSION,updatedAt:Date.now(),deviceId:meta.deviceId,clocks:meta.clocks||{},warriorState:{}};cloud.warriorState=state;cloud.clocks=meta.clocks||{};saveJson(CACHE_KEY,cloud);saveJson(META_KEY,meta);renderStatus()}

function redirectUri(){let p=location.pathname;if(p.endsWith('index.html'))p=p.slice(0,-10);if(!p.endsWith('/'))p+='/';return `${location.origin}${p}`}
function b64url(bytes){return btoa(String.fromCharCode(...new Uint8Array(bytes))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function rand(n=64){const a=new Uint8Array(n);crypto.getRandomValues(a);return b64url(a)}
async function sha256(s){return crypto.subtle.digest('SHA-256',new TextEncoder().encode(s))}
const AUTH_DB='warrior-mobile-auth-v01';
function authDb(){return new Promise((res,rej)=>{const r=indexedDB.open(AUTH_DB,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains('kv'))r.result.createObjectStore('kv')};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function authGet(k){const db=await authDb();try{return await new Promise((res,rej)=>{const r=db.transaction('kv','readonly').objectStore('kv').get(k);r.onsuccess=()=>res(r.result||null);r.onerror=()=>rej(r.error)})}finally{db.close()}}
async function authSet(k,v){const db=await authDb();try{await new Promise((res,rej)=>{const tx=db.transaction('kv','readwrite');tx.objectStore('kv').put(v,k);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)})}finally{db.close()}}
async function authClear(){const db=await authDb();try{await new Promise((res,rej)=>{const tx=db.transaction('kv','readwrite');tx.objectStore('kv').clear();tx.oncomplete=res;tx.onerror=()=>rej(tx.error)})}finally{db.close()}}
async function login(){cfg=loadJson(CFG_KEY,cfg);if(!cfg.clientId){cfg={...cfg,clientId:DEFAULT_MS_CLIENT_ID};saveJson(CFG_KEY,cfg)}if(!cfg.clientId){setView('setup');renderStatus({kind:'error',text:'Enter Microsoft client ID first'});return}const verifier=rand(64),challenge=b64url(await sha256(verifier)),stateId=rand(24);sessionStorage.setItem('pkceVerifier',verifier);sessionStorage.setItem('oauthState',stateId);const u=new URL(`https://login.microsoftonline.com/${encodeURIComponent(cfg.tenant||'common')}/oauth2/v2.0/authorize`);u.search=new URLSearchParams({client_id:cfg.clientId,response_type:'code',redirect_uri:redirectUri(),response_mode:'query',scope:AUTH_SCOPES,state:stateId,code_challenge:challenge,code_challenge_method:'S256',prompt:'select_account'}).toString();location.href=u.toString()}
async function handleOAuthCallback(){const q=new URLSearchParams(location.search),code=q.get('code'),err=q.get('error');if(err){renderStatus({kind:'error',text:`Microsoft login: ${q.get('error_description')||err}`});history.replaceState({},'',redirectUri());return}if(!code)return;const st=q.get('state'),expected=sessionStorage.getItem('oauthState'),verifier=sessionStorage.getItem('pkceVerifier');if(!verifier||st!==expected)throw new Error('OAuth state mismatch');cfg=loadJson(CFG_KEY,cfg);const body=new URLSearchParams({client_id:cfg.clientId,grant_type:'authorization_code',code,redirect_uri:redirectUri(),code_verifier:verifier,scope:AUTH_SCOPES});const r=await fetch(`https://login.microsoftonline.com/${encodeURIComponent(cfg.tenant||'common')}/oauth2/v2.0/token`,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});const tok=await r.json();if(!r.ok)throw new Error(tok.error_description||tok.error||'Token exchange failed');await storeTokens(tok);history.replaceState({},'',redirectUri());await syncNow()}
async function storeTokens(tok){const cur=await authGet('tokens')||{};await authSet('tokens',{...cur,...tok,expires_at:Date.now()+Math.max(60,Number(tok.expires_in||3600)-60)*1000})}
async function accessToken(){let t=await authGet('tokens');if(t?.access_token&&Date.now()<Number(t.expires_at||0))return t.access_token;if(t?.refresh_token){cfg=loadJson(CFG_KEY,cfg);const body=new URLSearchParams({client_id:cfg.clientId,grant_type:'refresh_token',refresh_token:t.refresh_token,redirect_uri:redirectUri(),scope:AUTH_SCOPES});const r=await fetch(`https://login.microsoftonline.com/${encodeURIComponent(cfg.tenant||'common')}/oauth2/v2.0/token`,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});const j=await r.json();if(r.ok){await storeTokens(j);return j.access_token}}return null}
async function graph(url,opts={}){const token=await accessToken();if(!token)throw new Error('Sign in with Microsoft first');const full=/^https?:/i.test(url)?url:`https://graph.microsoft.com/v1.0${url}`;return fetch(full,{...opts,headers:{Authorization:`Bearer ${token}`,...(opts.headers||{})}})}
async function getAccount(){const t=await accessToken();if(!t)return null;const r=await graph('/me');return r.ok?r.json():null}
function rootFolderParts(){return String(cfg.folder||'').split('/').filter(Boolean)}
function legacyGraphFilePath(){return `/me/drive/root:/${graphPath([...rootFolderParts(),FILE_NAME])}:/content`}
function deviceFileName(){return `device-${String(meta.deviceId||'mobile').replace(/[^a-zA-Z0-9._-]/g,'_').slice(0,96)}.json`}
function deviceGraphFilePath(){return `/me/drive/root:/${graphPath([...rootFolderParts(),DEVICE_DIR,deviceFileName()])}:/content`}
async function ensureSyncDeviceFolder(){const parts=rootFolderParts(),parent=`/me/drive/root:/${graphPath(parts)}:/children`,target=`/me/drive/root:/${graphPath([...parts,DEVICE_DIR])}`;let r=await graph(target);if(r.ok)return;if(r.status!==404)throw new Error(`Sync folder check failed (${r.status})`);r=await graph(parent,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:DEVICE_DIR,folder:{},'@microsoft.graph.conflictBehavior':'fail'})});if(!r.ok&&r.status!==409)throw new Error(`Could not create conflict-safe sync folder (${r.status})`)}
async function fetchJsonContent(url,{quiet=false}={}){const r=await graph(url,{cache:'no-store'});if(r.status===404&&quiet)return null;if(!r.ok){if(quiet)return null;throw new Error(`OneDrive read failed (${r.status})`)}const j=await r.json();if(Number(j.schema)!==SCHEMA||!j.warriorState){if(quiet)return null;throw new Error('Unsupported Warrior Hub sync file')}return j}
async function listDeviceSnapshots(){const out=[];const target=`/me/drive/root:/${graphPath([...rootFolderParts(),DEVICE_DIR])}`;let test=await graph(target);if(test.status===404)return out;if(!test.ok)throw new Error(`OneDrive device folder read failed (${test.status})`);let url=`${target}:/children?$top=200&$select=id,name,size,lastModifiedDateTime`;while(url){const r=await graph(url);if(!r.ok)throw new Error(`OneDrive device list failed (${r.status})`);const j=await r.json();for(const f of j.value||[]){if(!/\.json$/i.test(f.name||''))continue;const data=await fetchJsonContent(`/me/drive/items/${encodeURIComponent(f.id)}/content`,{quiet:true});if(data)out.push(data)}url=j['@odata.nextLink']||''}return out}
async function fetchCloudSnapshots(){const out=[];const legacy=await fetchJsonContent(legacyGraphFilePath(),{quiet:true});if(legacy)out.push(legacy);out.push(...await listDeviceSnapshots());const seen=new Set(),dedup=[];for(const x of out){const k=`${x.deviceId||''}|${Number(x.updatedAt||0)}|${JSON.stringify(x.clocks||{}).length}|${JSON.stringify(x.warriorState||{}).length}`;if(seen.has(k))continue;seen.add(k);dedup.push(x)}dedup.sort((a,b)=>Number(a.updatedAt||0)-Number(b.updatedAt||0));return dedup}
async function writeDeviceCloud(payload){await ensureSyncDeviceFolder();const r=await graph(deviceGraphFilePath(),{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!r.ok)throw new Error(`OneDrive device write failed (${r.status})`);return r.json().catch(()=>null)}
async function syncNow(){cfg=loadJson(CFG_KEY,cfg);$('#syncNowBtn').disabled=true;renderStatus({text:'OneDrive: conflict-safe syncing…'});try{const snapshots=await fetchCloudSnapshots(),local=state||{};let merged=local,clocks={...(meta.clocks||{})};for(const remote of snapshots){const res=merge(merged,remote.warriorState||{},clocks,remote.clocks||{},remote.updatedAt||0);merged=res.state;clocks=res.clocks}state=merged;meta.clocks=clocks;const own=snapshots.find(x=>String(x.deviceId||'')===String(meta.deviceId||''));const changed=!own||JSON.stringify(state)!==JSON.stringify(own.warriorState||{})||JSON.stringify(meta.clocks)!==JSON.stringify(own.clocks||{});let payload=own||null;if(changed){payload={schema:SCHEMA,app:'Warrior Hub',syncMode:'device-shard-v1',version:`mobile-${APP_VERSION}`,updatedAt:Date.now(),deviceId:meta.deviceId,clocks:meta.clocks,warriorState:state};await writeDeviceCloud(payload)}if(!payload)payload={schema:SCHEMA,app:'Warrior Hub',version:`mobile-${APP_VERSION}`,updatedAt:Date.now(),deviceId:meta.deviceId,clocks:meta.clocks,warriorState:state};cloud=payload;meta.lastSyncAt=Date.now();meta.shardedSync=true;saveLocalCloud();renderAll();renderStatus({kind:'ok',text:`OneDrive conflict-safe sync · ${state.assignments?.length||0} assignments`});flushDrawingCloud().catch(e=>log('drawing-backup-after-sync',{error:String(e)}));log('sync-success',{changed,updatedAt:payload.updatedAt,snapshotCount:snapshots.length,deviceFile:deviceFileName()})}catch(e){log('sync-error',{error:String(e.message||e)});renderStatus({kind:'error',text:String(e.message||e)})}finally{$('#syncNowBtn').disabled=false}}
function schedulePush(ms=1000){clearTimeout(pushTimer);pushTimer=setTimeout(syncNow,ms)}

/* ---------- v0.6 live desktop Study + Spotify remote ---------- */
function remoteFilePath(name){return `/me/drive/root:/${graphPath([...rootFolderParts(),name])}:/content`}
function remoteFolderPath(name){return `/me/drive/root:/${graphPath([...rootFolderParts(),name])}`}
function remoteIsFresh(){return !!remoteLive&&Date.now()-Number(remoteLive.at||0)<REMOTE_STALE_MS}
function remoteRemaining(){const s=remoteLive?.study||{};if(s.running&&s.endAt)return Math.max(0,Number(s.endAt)-Date.now());return Math.max(0,Number(s.remainingMs)||0)}
function remoteTime(ms){const total=Math.max(0,Math.ceil(Number(ms||0)/1000)),m=Math.floor(total/60),s=total%60;return `${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}
function remotePosition(){const p=remoteLive?.spotify||{},base=Math.max(0,Number(p.position)||0),dur=Math.max(0,Number(p.duration)||0),stamp=Number(p.at)||Date.now();const est=base+(p.playing&&p.progressConfirmed?Math.max(0,Date.now()-stamp)/1000:0);return dur?Math.min(dur,est):est}
async function fetchRemoteLive({quiet=true}={}){if(remoteFetchBusy)return remoteLive;remoteFetchBusy=true;try{const r=await graph(remoteFilePath(REMOTE_LIVE_FILE),{cache:'no-store'});if(r.status===404){remoteLive=null;remoteLastError='Desktop bridge has not published yet';return null}if(!r.ok)throw new Error(`Desktop bridge read failed (${r.status})`);const j=await r.json();remoteLive=j?.type==='warrior-mobile-live'?j:null;remoteLastError='';if(currentView==='study')renderRemoteStudy();if(currentView==='today')renderTimer();return remoteLive}catch(e){remoteLastError=String(e.message||e);if(!quiet)renderStatus({kind:'error',text:remoteLastError});return null}finally{remoteFetchBusy=false}}
async function ensureRemoteCommandFolder(){const target=remoteFolderPath(REMOTE_COMMAND_DIR),parent=`/me/drive/root:/${graphPath(rootFolderParts())}:/children`;let r=await graph(target);if(r.ok)return;if(r.status!==404)throw new Error(`Remote command folder check failed (${r.status})`);r=await graph(parent,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:REMOTE_COMMAND_DIR,folder:{},'@microsoft.graph.conflictBehavior':'fail'})});if(!r.ok&&r.status!==409)throw new Error(`Could not create remote command folder (${r.status})`)}
async function sendRemoteCommand(action,payload={}){if(remoteCommandBusy&&/^study\./.test(action))return false;const token=await accessToken();if(!token){setView('setup');renderStatus({kind:'error',text:'Sign in with Microsoft to control the desktop'});return false}if(/^study\./.test(action))remoteCommandBusy=true;try{await ensureRemoteCommandFolder();const seq=`${Date.now()}-${Math.random().toString(36).slice(2,9)}`,name=`cmd-${String(Date.now()).padStart(13,'0')}-${seq.slice(-7)}.json`;const cmd={schema:1,type:'warrior-mobile-command',seq,at:Date.now(),deviceId:meta.deviceId,action,payload};const path=`/me/drive/root:/${graphPath([...rootFolderParts(),REMOTE_COMMAND_DIR,name])}:/content`;const r=await graph(path,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(cmd)});if(!r.ok)throw new Error(`Remote command failed (${r.status})`);setTimeout(()=>fetchRemoteLive().catch(()=>{}),500);return true}catch(e){remoteLastError=String(e.message||e);renderRemoteStudy();return false}finally{remoteCommandBusy=false}}
function spotifyUiTime(sec){const s=Math.max(0,Math.floor(Number(sec)||0)),m=Math.floor(s/60);return `${m}:${String(s%60).padStart(2,'0')}`}
function renderRemoteStudy(){const online=remoteIsFresh(),s=remoteLive?.study||{},p=remoteLive?.spotify||{},phase=s.phase==='break'?'BREAK':'FOCUS',remaining=remoteRemaining();const status=$('#remoteDesktopStatus');if(status){status.textContent=online?'Desktop connected':(remoteLastError||'Waiting for desktop…');status.className=`remote-status ${online?'online':'offline'}`}const phaseEl=$('#remotePhase');if(phaseEl)phaseEl.textContent=phase;const timeEl=$('#remoteTimerText');if(timeEl)timeEl.textContent=online?remoteTime(remaining):'--:--';const cycle=$('#remoteCycle');if(cycle)cycle.textContent=online?`Cycle ${Math.max(0,Number(s.cycles)||0)+1} · ${s.autoAdvance===false?'manual next':'auto advance'}`:'Open Warrior Hub on your PC and keep OneDrive connected.';const toggle=$('#remoteTimerToggle');if(toggle){toggle.textContent=s.running?'Pause':'Start';toggle.disabled=!online}const skip=$('#remoteTimerSkip'),reset=$('#remoteTimerReset');if(skip)skip.disabled=!online;if(reset)reset.disabled=!online;const art=$('#remoteSpotifyArt');if(art)art.innerHTML=p.artwork?`<img src="${esc(p.artwork)}" alt="">`:'♫';const title=$('#remoteSpotifyTitle');if(title)title.textContent=p.title||'Spotify on desktop';const artist=$('#remoteSpotifyArtist');if(artist)artist.textContent=p.artist||(online?'Waiting for track metadata…':'Desktop offline');const dur=Math.max(0,Number(p.duration)||0),pos=remotePosition(),pct=dur?Math.max(0,Math.min(100,pos/dur*100)):0,fill=$('#remoteSpotifyProgressFill');if(fill)fill.style.width=`${pct}%`;const t=$('#remoteSpotifyTime');if(t)t.textContent=dur?`${spotifyUiTime(pos)} · −${spotifyUiTime(Math.max(0,dur-pos))}`:'';const play=$('#remoteSpotifyToggle');if(play){play.textContent=p.playing?'Ⅱ':'▶';play.disabled=!online}const prev=$('#remoteSpotifyPrev'),next=$('#remoteSpotifyNext'),shuffle=$('#remoteSpotifyShuffle');if(prev)prev.disabled=!online;if(next)next.disabled=!online;if(shuffle){shuffle.disabled=!online;shuffle.classList.toggle('active',!!p.shuffleOn);shuffle.textContent=p.shuffleOn?'Shuffle On':'Shuffle'}document.body.classList.toggle('remote-break',online&&s.phase==='break')}
function startRemotePolling(){clearInterval(remotePollTimer);remotePollTimer=setInterval(()=>{if(document.visibilityState==='visible')fetchRemoteLive().catch(()=>{})},REMOTE_POLL_MS);fetchRemoteLive().catch(()=>{})}
function vapidKeyBytes(s){let b=String(s).replace(/-/g,'+').replace(/_/g,'/');while(b.length%4)b+='=';const raw=atob(b),out=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)out[i]=raw.charCodeAt(i);return out}
async function pushSubscription(){if(!('serviceWorker'in navigator)||!('PushManager'in window))return null;const reg=await navigator.serviceWorker.ready;return reg.pushManager.getSubscription()}
async function savePushSubscription(sub){if(!sub)return false;const token=await accessToken();if(!token)throw new Error('Sign in with Microsoft first');const body={schema:1,type:'warrior-mobile-push',appVersion:APP_VERSION,deviceId:meta.deviceId,at:Date.now(),subscription:sub.toJSON()};const r=await graph(remoteFilePath(REMOTE_PUSH_FILE),{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw new Error(`Phone alert registration failed (${r.status})`);return true}
async function enablePhoneAlerts(){const status=$('#phoneAlertsStatus'),btn=$('#enablePhoneAlertsBtn');if(btn)btn.disabled=true;try{if(!window.isSecureContext||!('serviceWorker'in navigator)||!('PushManager'in window)||!('Notification'in window))throw new Error('Web Push is not available here. Open the installed Home Screen app.');if(Notification.permission!=='granted'){const p=await Notification.requestPermission();if(p!=='granted')throw new Error('Notifications were not allowed')}const reg=await navigator.serviceWorker.ready;let sub=await reg.pushManager.getSubscription();if(!sub)sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:vapidKeyBytes(MOBILE_VAPID_PUBLIC_KEY)});await savePushSubscription(sub);if(status)status.textContent='Phone alerts ON · Focus/Break can notify while the app is closed';if(btn)btn.textContent='Refresh phone alerts'}catch(e){if(status)status.textContent=String(e.message||e)}finally{if(btn)btn.disabled=false}}
async function refreshPhoneAlertStatus(){const status=$('#phoneAlertsStatus'),btn=$('#enablePhoneAlertsBtn');if(!status||!btn)return;if(!('PushManager'in window)||!('Notification'in window)){status.textContent='Push alerts unsupported here';btn.disabled=true;return}const sub=await pushSubscription().catch(()=>null);if(Notification.permission==='granted'&&sub){status.textContent='Phone alerts ON';btn.textContent='Refresh phone alerts';if(await accessToken())savePushSubscription(sub).catch(()=>{})}else{status.textContent=Notification.permission==='denied'?'Notifications are blocked in iOS settings':'Enable once for Focus/Break alerts while closed';btn.textContent='Enable phone alerts'}}


function bind(){
  $$('.tab').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));$('#syncNowBtn').addEventListener('click',syncNow);$('#assignmentFilter').addEventListener('change',renderAssignments);$('#assignmentSearch').addEventListener('input',renderAssignments);$('#calPrev').addEventListener('click',()=>{calCursor=new Date(calCursor.getFullYear(),calCursor.getMonth()-1,1);renderCalendar()});$('#calNext').addEventListener('click',()=>{calCursor=new Date(calCursor.getFullYear(),calCursor.getMonth()+1,1);renderCalendar()});$('#calendarGrid').addEventListener('click',e=>{const b=e.target.closest('[data-date]');if(b){calSelected=b.dataset.date;renderCalendar()}});$('#dayTabs').addEventListener('click',e=>{const b=e.target.closest('[data-day]');if(b){selectedDay=b.dataset.day;renderSchedule()}});
  $('#notesCourse').addEventListener('change',()=>switchDrawContext($('#notesCourse').value,drawDate));$('#notesDate').addEventListener('change',()=>switchDrawContext(drawCourse,$('#notesDate').value));$('#prevNoteDayBtn').addEventListener('click',()=>switchDrawContext(drawCourse,addDays(drawDate,-1)));$('#nextNoteDayBtn').addEventListener('click',()=>switchDrawContext(drawCourse,addDays(drawDate,1)));$('#todayNoteBtn').addEventListener('click',()=>switchDrawContext(drawCourse,localDateKey(new Date())));$('#noteDayChips').addEventListener('click',e=>{const b=e.target.closest('[data-note-date]');if(b)switchDrawContext(drawCourse,b.dataset.noteDate)});$('#prevCourseBtn').addEventListener('click',()=>cycleCourse(-1));$('#nextCourseBtn').addEventListener('click',()=>cycleCourse(1));
  $$('.draw-tool').forEach(b=>b.addEventListener('click',()=>{$$('.draw-tool').forEach(x=>x.classList.remove('active'));b.classList.add('active');drawTool=b.dataset.tool;selectedItemId='';itemGesture=null;$$('#infinitePaper canvas').forEach(c=>c.classList.toggle('select-mode',drawTool==='select'));updateItemTools();const c=activeCanvas();if(c)drawPageToCanvas(activePage,c)}));$('#drawColor').addEventListener('input',e=>drawColor=e.target.value);$('#drawWidth').addEventListener('input',e=>drawWidth=Number(e.target.value)||4);$('#paperStyle').addEventListener('change',async e=>{if(!activePage)return;activePage.paper=e.target.value;activePageChanged=true;const c=activeCanvas();if(c)drawPageToCanvas(activePage,c);await saveActiveDrawing({checkpoint:true})});$('#fingerDrawBtn').addEventListener('click',()=>{fingerDraw=!fingerDraw;$('#fingerDrawBtn').setAttribute('aria-pressed',String(fingerDraw));$('#fingerDrawBtn').textContent=fingerDraw?'☝ Draw':'☝ Pan';$$('#infinitePaper canvas').forEach(c=>c.classList.toggle('finger-draw',fingerDraw))});$('#undoDrawBtn').addEventListener('click',undoDrawing);$('#redoDrawBtn').addEventListener('click',redoDrawing);
  $('#insertNoteItemBtn').addEventListener('click',openInsertSheet);$('#closeInsertBtn').addEventListener('click',closeInsertSheet);$('#closeInsertBackdrop').addEventListener('click',closeInsertSheet);$('#pickPhotosBtn').addEventListener('click',()=>$('#photoPickerInput').click());$('#takePhotoBtn').addEventListener('click',()=>$('#cameraPickerInput').click());$('#pickFilesBtn').addEventListener('click',()=>$('#noteFilePickerInput').click());$('#pasteImageBtn').addEventListener('click',pasteFromClipboard);$('#deleteItemBtn').addEventListener('click',deleteSelectedItem);$('#fitItemBtn').addEventListener('click',fitSelectedItem);$('#openItemBtn').addEventListener('click',()=>openSelectedItem().catch(e=>noteStatus(String(e.message||e),'error')));
  for(const [id,source] of [['photoPickerInput','photos'],['cameraPickerInput','camera'],['noteFilePickerInput','files']]){$(`#${id}`).addEventListener('change',e=>{const files=e.target.files;if(files?.length)insertFiles(files,{source}).catch(err=>noteStatus(String(err.message||err),'error'));e.target.value=''})}
  const vp=$('#drawingViewport');vp.addEventListener('dragover',e=>{e.preventDefault();vp.classList.add('drag-over')});vp.addEventListener('dragleave',()=>vp.classList.remove('drag-over'));vp.addEventListener('drop',e=>{e.preventDefault();vp.classList.remove('drag-over');if(e.dataTransfer?.files?.length)insertFiles(e.dataTransfer.files,{source:'drop'}).catch(err=>noteStatus(String(err.message||err),'error'))});document.addEventListener('paste',e=>{const files=[...(e.clipboardData?.files||[])].filter(f=>f.type.startsWith('image/'));if(files.length&&currentView==='notes'){e.preventDefault();insertFiles(files,{source:'paste-event'}).catch(err=>noteStatus(String(err.message||err),'error'))}});
  $('#saveNotesBtn').addEventListener('click',saveNote);$('#timerToggle').addEventListener('click',toggleTimer);$('#timerReset').addEventListener('click',resetTimer);$('#remoteTimerToggle')?.addEventListener('click',()=>sendRemoteCommand(`study.${remoteLive?.study?.running?'pause':'start'}`));$('#remoteTimerSkip')?.addEventListener('click',()=>sendRemoteCommand('study.skip'));$('#remoteTimerReset')?.addEventListener('click',()=>sendRemoteCommand('study.reset'));$('#remoteSpotifyPrev')?.addEventListener('click',()=>sendRemoteCommand('spotify.previous'));$('#remoteSpotifyToggle')?.addEventListener('click',()=>sendRemoteCommand(`spotify.${remoteLive?.spotify?.playing?'pause':'resume'}`));$('#remoteSpotifyNext')?.addEventListener('click',()=>sendRemoteCommand('spotify.next'));$('#remoteSpotifyShuffle')?.addEventListener('click',()=>sendRemoteCommand('spotify.shuffle',{value:!remoteLive?.spotify?.shuffleOn}));$('#enablePhoneAlertsBtn')?.addEventListener('click',enablePhoneAlerts);$('#saveSetupBtn').addEventListener('click',()=>{cfg={clientId:$('#clientIdInput').value.trim()||DEFAULT_MS_CLIENT_ID,folder:$('#folderInput').value.trim()||'WARRIOR HUB',tenant:$('#tenantInput').value.trim()||'common'};saveJson(CFG_KEY,cfg);renderStatus({kind:'ok',text:'Setup saved'});renderSetup()});$('#loginBtn').addEventListener('click',login);$('#logoutBtn').addEventListener('click',async()=>{await authClear();renderSetup();renderStatus({text:'Signed out'})});$('#copyRedirectBtn').addEventListener('click',async()=>{await navigator.clipboard.writeText(redirectUri());$('#copyRedirectBtn').textContent='Copied';setTimeout(()=>$('#copyRedirectBtn').textContent='Copy',1000)});
  $('#backupNotesNowBtn').addEventListener('click',()=>flushDrawingCloud().catch(e=>$('#noteSafetyStatus').textContent=String(e.message||e)));$('#restoreCloudNotesBtn').addEventListener('click',()=>restoreCloudNotes().catch(e=>{$('#noteSafetyStatus').textContent=String(e.message||e);noteStatus('Restore error','error')}));$('#exportNotesBackupBtn').addEventListener('click',exportNotesBackup);$('#importNotesBackupInput').addEventListener('change',e=>{const f=e.target.files?.[0];if(f)importNotesBackup(f).catch(err=>$('#noteSafetyStatus').textContent=String(err.message||err));e.target.value=''});
  $('#exportMobileDebug').addEventListener('click',async()=>{const pages=await noteAll('pages').catch(()=>[]),assets=await noteAll('assets').catch(()=>[]);const blob=new Blob([JSON.stringify({app:'Warrior Hub Mobile',version:APP_VERSION,at:new Date().toISOString(),config:{...cfg,clientId:cfg.clientId?`${cfg.clientId.slice(0,6)}…`:''},meta,stateSummary:{assignments:state.assignments?.length||0,schedule:state.schedule?.length||0,courses:state.courses?.length||0,drawingPages:pages.length,dirtyDrawingPages:pages.filter(p=>p.dirty).length,noteAssets:assets.length,dirtyNoteAssets:assets.filter(a=>a.dirty).length},events:debug},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`warrior-mobile-debug-${Date.now()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)});
  document.body.addEventListener('click',e=>{const c=e.target.closest('[data-open]');if(c&&c.dataset.open)window.open(c.dataset.open,'_blank')});window.addEventListener('beforeunload',()=>{if(activePage&&activePageChanged){activePage.rev=(Number(activePage.rev)||0)+1;activePage.dirty=true;activePage.updatedAt=new Date().toISOString();notePut('pages',activePage).catch(()=>{})}});document.addEventListener('visibilitychange',()=>{if(document.hidden){if(activePageChanged)saveActiveDrawing({checkpoint:true,cloud:false}).catch(()=>{});flushDrawingCloud().catch(()=>{})}})
}
function cycleCourse(delta){const opts=courseOptions(),i=Math.max(0,opts.findIndex(([id])=>id===drawCourse)),n=(i+delta+opts.length)%opts.length;switchDrawContext(opts[n][0],drawDate)}

async function boot(){bind();bindDrawing();startTimerLoop();startRemotePolling();$('#redirectUriText').textContent=redirectUri();if(navigator.storage?.persist)navigator.storage.persist().then(ok=>log('storage-persist',{ok})).catch(()=>{});if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(e=>log('sw-error',{error:String(e)}));try{await handleOAuthCallback()}catch(e){log('oauth-error',{error:String(e)});renderStatus({kind:'error',text:String(e.message||e)})}drawCourse=preferredCourse();await ensurePages();const hash=String(location.hash||'').replace('#','');if(hash==='study')currentView='study';renderAll();if((cfg.clientId||DEFAULT_MS_CLIENT_ID)&&await accessToken()){if(!cfg.clientId){cfg={...cfg,clientId:DEFAULT_MS_CLIENT_ID};saveJson(CFG_KEY,cfg)}await syncNow();fetchRemoteLive().catch(()=>{});refreshPhoneAlertStatus().catch(()=>{})}}
boot();
})();
