const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const files=new Map();let seq=0;
const source=fs.readFileSync(path.join(__dirname,'../desktop-notes/desktop_music.js'),'utf8').replace('panel();setInterval(render,500);','').replace(/\(async\(\)=>\{await identity\(\);while\(!stopped\)[\s\S]*?\}\)\(\)\.catch\(error=>console.warn\('Desktop music sync',error\)\);/,'').replace('window.WarriorDesktopMusic={remote:()=>selected,send,cycle};','window.WarriorDesktopMusic={remote:()=>selected,send,cycle,accept};');
function response(status,data){return{status,ok:status>=200&&status<300,json:async()=>data}}
async function graphFetch(url,options={}){
 const u=new URL(url,'https://graph.microsoft.com/v1.0'),p=decodeURIComponent(u.pathname.replace('/v1.0','')),method=options.method||'GET';
 if(p.startsWith('/me/drive/items/')){const id=p.split('/')[4],key=[...files.keys()].find(k=>files.get(k).id===id);if(method==='DELETE'){if(key)files.delete(key);return response(204,{})}return response(key?200:404,key?files.get(key).body:{})}
 if(p.endsWith(':/content')){const key=p.slice('/me/drive/root:/'.length,-':/content'.length);if(method==='PUT'){files.set(key,{id:files.get(key)?.id||String(++seq),body:JSON.parse(options.body)});return response(200,{})}return response(files.has(key)?200:404,files.get(key)?.body||{})}
 if(p.endsWith(':/children')){const parent=p.slice('/me/drive/root:/'.length,-':/children'.length);return response(200,{value:[...files.entries()].filter(([key])=>key.slice(0,key.lastIndexOf('/'))===parent).map(([key,value])=>({id:value.id,name:key.split('/').at(-1)}))})}
 return response(200,{folder:{}});
}
const tick=()=>new Promise(resolve=>setImmediate(resolve));
function device(id,playing){const store={warriorOneDriveDeviceIdV51:id,warriorDesktopDeviceNameV1:id==='desktop-A'?'Desktop':'Laptop',warriorSpotifyStudySessionV52:{at:Date.now()},warriorSpotifyPlayerStateV59:playing?{trackId:'track-A',title:'Hip Shop',artist:'Toby Fox',playing:true,at:Date.now(),position:12,duration:180}:{}};const events=[],writes=[];
 const context={console,crypto,URL,Date,Map,Set,Math,JSON,Number,String,Promise,encodeURIComponent,setTimeout,setInterval:()=>0,navigator:{},document:{querySelector:()=>null},chrome:{storage:{local:{get:async keys=>Object.fromEntries((Array.isArray(keys)?keys:[keys]).map(k=>[k,store[k]])),set:async values=>{const changes={};for(const[k,value]of Object.entries(values)){if(k==='warriorSpotifyPlayerCommandV59')writes.push(value);changes[k]={newValue:value};store[k]=value}for(const event of events)event(changes,'local')}},onChanged:{addListener:fn=>events.push(fn)}}},addEventListener:()=>{}};context.window=context;context.WarriorMobileBridge={graphAccessToken:async()=>'token',graphFetch};context.WarriorOneDriveSync={getDirectoryHandle:async()=>null};vm.runInNewContext(source,context);return{context,store,writes,music:context.WarriorDesktopMusic}}
(async()=>{
 const a=device('desktop-A',true),b=device('laptop-B',false);await a.music.cycle();await b.music.cycle();assert.equal(b.music.remote().deviceId,'desktop-A');assert.equal(a.music.remote(),null);assert.equal(b.music.remote().spotify.title,'Hip Shop');
 await b.music.send({action:'next'});const key=[...files.keys()].find(x=>x.includes('commands/cmd-desktop-A-'));assert(key);const duplicate=files.get(key).body;await b.music.cycle();assert(files.has(key),'Laptop must leave Desktop commands untouched');assert.equal(b.writes.length,0);await a.music.cycle();assert.equal(a.writes.length,1);assert.equal(a.writes[0].action,'next');assert(!files.has(key));await a.music.accept(duplicate);assert.equal(a.writes.length,1,'Repeated command does not switch a second track');
 await b.music.send({action:'seekRatio',ratio:.6});await a.music.cycle();assert.equal(a.writes.at(-1).ratio,.6);
 a.store.warriorSpotifyPlayerStateV59={...a.store.warriorSpotifyPlayerStateV59,playing:false,at:Date.now()};await a.music.cycle();await b.music.cycle();assert.equal(b.music.remote().spotify.playing,false);await b.music.send({action:'resume'});await a.music.cycle();assert.equal(a.writes.at(-1).action,'resume');
 const ownKey='WARRIOR HUB/warrior-desktop-music/desktop-A.json';files.get(ownKey).body.at=Date.now()-60000;await b.music.cycle();assert.equal(b.music.remote(),null,'Stale PC disappears');await assert.rejects(()=>b.music.send({action:'next'}),/offline/);
 const update=fs.readFileSync(path.join(__dirname,'../desktop-notes/onedrive_update.js'),'utf8');for(const m of update.matchAll(/showDirectoryPicker\(\{id:'([^']+)'/g))assert(m[1].length<=32);
 console.log('PASS two PCs: automatic remote track discovery, target-only next/pause/resume/seek, no duplicate commands, paused owner retained, stale host expiry, valid update folder picker IDs');
})().catch(error=>{console.error(error);process.exit(1)});
