const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?path.join(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES,'playwright'):'playwright');
(async()=>{let dir=path.resolve(process.env.WARRIOR_EXTENSION_ROOT||path.join(__dirname,'../v61'));
 if(process.env.WARRIOR_BROWSER_FIXTURE){const source=dir;dir=fs.mkdtempSync(path.join(os.tmpdir(),'warrior-fixture-'));fs.cpSync(source,dir,{recursive:true});fs.copyFileSync(path.join(__dirname,'legacy-background-fixture.js'),path.join(dir,'background.js'));fs.mkdirSync(path.join(dir,'icons'),{recursive:true});const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jZ1kAAAAASUVORK5CYII=','base64');for(const size of [16,32,48,128])fs.writeFileSync(path.join(dir,'icons',`icon${size}.png`),png)}
 const context=await chromium.launchPersistentContext('',{channel:'chromium',headless:true,args:['--no-sandbox','--disable-extensions-except='+dir,'--load-extension='+dir]});
 try{const worker=context.serviceWorkers()[0]||await context.waitForEvent('serviceworker');const errors=[];worker.on('console',m=>{if(m.type()==='error')errors.push(m.text())});const id=new URL(worker.url()).host;
 await context.route('https://open.spotify.com/**',r=>r.fulfill({status:200,contentType:'text/html',body:'<!doctype html><title>Music test</title>'}));
 const result=await worker.evaluate(async()=>({version:chrome.runtime.getManifest().version,runtime:typeof WarriorBackgroundRuntime.execute,sync:typeof WarriorOneDriveSync.syncNow,music:typeof WarriorDesktopMusic.cycle,alarm:await chrome.alarms.get('warrior-cloud-v61')}));assert.equal(result.version,'5.19.61');assert.equal(result.runtime,'function');assert(result.alarm);
 const page=await context.newPage(),uiErrors=[];page.on('pageerror',error=>uiErrors.push(error.message));await page.goto('chrome-extension://'+id+'/sidepanel.html');await page.waitForFunction(()=>typeof state!=='undefined'&&Array.isArray(state?.todos)).catch(error=>{console.log('UI errors',uiErrors);throw error});
 await page.evaluate(async()=>{const r=await chrome.runtime.sendMessage({type:'ADD_TODO',title:'Browser test task'});if(!r.ok)throw new Error(r.error)});
 await page.waitForFunction(()=>document.body.textContent.includes('Browser test task'));
 const ensured=await worker.evaluate(async()=>{await Promise.all([WarriorBackgroundRuntime.ensureEngine(),WarriorBackgroundRuntime.ensureEngine()]);return chrome.tabs.query({url:chrome.runtime.getURL('spotify-engine.html')})});assert.equal(ensured.length,1);assert.equal(ensured[0].autoDiscardable,false);
 await page.close();assert.equal((await worker.evaluate(()=>chrome.tabs.query({url:chrome.runtime.getURL('spotify-engine.html')}))).length,1);
 const controller=await context.newPage();controller.on('pageerror',error=>uiErrors.push(error.message));await controller.goto('chrome-extension://'+id+'/sidepanel.html');const reply=await controller.evaluate(()=>chrome.runtime.sendMessage({type:'WARRIOR_RUNTIME_SYNC'}));assert.equal(reply.ok,true,'legacy Unknown reply must not race background runtime');
 assert.deepEqual(uiErrors,[]);assert.deepEqual(errors,[]);console.log('PASS: Chromium loads worker, alarm, task UI, one persistent engine; closing panel preserves engine; runtime replies correctly');
 }finally{await context.close()}})().catch(error=>{console.error(error);process.exitCode=1});
