const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium,webkit}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?path.join(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES,'playwright'):'playwright');
const root=path.join(__dirname,'..'),files=new Map();let seq=0,failCloud=false;
const api=`window.__sync={connectNotes,restoreCloudNotes,noteAll,noteGet,notePut,pagesFor,saveActiveDrawing,finishNoteInteraction,notebookPDFBlob,showNotebookActions,trashNotebook,get:()=>({activePage,drawCourse,drawDate,state:notesConnectionState}),change:fn=>{fn(activePage);activePageChanged=true},token:()=>authSet('tokens',{access_token:'fixture',expires_at:Date.now()+3600000}),expire:()=>authSet('tokens',{access_token:'expired',refresh_token:'fixture-refresh',expires_at:0}),device:id=>{meta.deviceId=id}};\n`;
const source=fs.readFileSync(path.join(root,'app.js'),'utf8');
const server=http.createServer((req,res)=>{const name=new URL(req.url,'http://localhost').pathname.slice(1)||'index.html';if(name.includes('..'))return res.writeHead(400).end();let content;try{content=fs.readFileSync(path.join(root,name))}catch{return res.writeHead(404).end()}if(name==='app.js')content=source.replace('boot().catch(',api+'boot().catch(');res.setHeader('Content-Type',name.endsWith('.js')?'text/javascript':name.endsWith('.css')?'text/css':name.endsWith('.html')?'text/html':'application/json');res.end(content)});
async function cloudRoute(route){
  const req=route.request(),url=new URL(req.url()),pathname=decodeURIComponent(url.pathname.replace('/v1.0','')),method=req.method();
  const reply=(status,body)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(body)});
  if(failCloud)return reply(503,{error:'fixture unavailable'});
  if(pathname.startsWith('/me/drive/items/')){const id=pathname.split('/')[4],entry=[...files.values()].find(f=>f.id===id);return entry?reply(200,entry.body):reply(404,{})}
  if(pathname.endsWith(':/content')){const key=pathname.slice('/me/drive/root:/'.length,-':/content'.length);if(method==='PUT'){const prior=files.get(key);files.set(key,{id:prior?.id||String(++seq),name:key.split('/').at(-1),key,body:JSON.parse(req.postData()||'{}')});return reply(200,{})}return files.has(key)?reply(200,files.get(key).body):reply(404,{})}
  if(pathname.endsWith(':/children')){const folder=pathname.slice('/me/drive/root:/'.length,-':/children'.length);return reply(200,{value:[...files.values()].filter(f=>f.key.slice(0,f.key.lastIndexOf('/'))===folder).map(f=>({id:f.id,name:f.name,size:100}))})}
  if(pathname.startsWith('/me/drive/root:'))return reply(200,{folder:{}});
  return reply(200,{});
}
(async()=>{
  await new Promise(r=>server.listen(0,'127.0.0.1',r));const url=`http://127.0.0.1:${server.address().port}`;
  const browser=await(process.env.NOTES_WEBKIT?webkit:chromium).launch({headless:true}),errors=[];
  const open=async(viewport,device)=>{const c=await browser.newContext({viewport,hasTouch:true,serviceWorkers:'block'});await c.route('https://graph.microsoft.com/**',cloudRoute);const p=await c.newPage();p.on('pageerror',e=>errors.push(e.message));await p.addInitScript(()=>localStorage.setItem('warriorAutoAuthRetryAfter',String(Date.now()+86400000)));await p.goto(url+'/#notes');await p.waitForFunction(()=>window.__sync&&document.querySelector('#notesLibrary')&&!document.querySelector('#notesLibrary').hidden);await p.waitForFunction(()=>__sync.get().state==='auth');await p.evaluate(async id=>{__sync.device(id);await __sync.token()},device);return{c,p}};
  const tablet=await open({width:1024,height:768},'tablet');
  await tablet.p.click('#newNotebookBtn');await tablet.p.fill('#newNotebookName','Shared Calculus');await tablet.p.click('#newNotebookForm button[type=submit]');await tablet.p.locator('#notesEditor').waitFor({state:'visible'});await tablet.p.waitForFunction(()=>__sync.get().activePage?.notebookTitle==='Shared Calculus');
  await tablet.p.evaluate(async()=>{__sync.change(p=>{p.strokes=[{id:'tablet-ink',tool:'pen',color:'#11151d',width:4,points:[{x:150,y:150,p:.5},{x:500,y:350,p:.5}]}];p.typedText='Notes from my tablet'});await __sync.finishNoteInteraction();await __sync.connectNotes({forcePull:true})});
  const key=await tablet.p.evaluate(()=>__sync.get().activePage.key);assert([...files.values()].some(f=>f.body?.page?.key===key));
  const pc=await open({width:1440,height:900},'desktop');await pc.p.evaluate(()=>__sync.connectNotes({forcePull:true}));await pc.p.locator('.notebook-file').waitFor();assert.equal(await pc.p.locator('.notebook-file b').textContent(),'Shared Calculus');await pc.p.click('.notebook-file');await pc.p.locator('#notesEditor').waitFor({state:'visible'});await pc.p.waitForFunction(key=>__sync.get().activePage?.key===key,key);
  assert.equal(await pc.p.evaluate(()=>__sync.get().activePage.strokes[0].id),'tablet-ink');assert.equal(await pc.p.evaluate(()=>__sync.get().activePage.typedText),'Notes from my tablet');
  await pc.p.reload();await pc.p.waitForFunction(()=>window.__sync&&__sync.get().state==='connected');await pc.p.locator('.notebook-file').waitFor();await pc.p.click('.notebook-file');await pc.p.locator('#notesEditor').waitFor({state:'visible'});await pc.p.waitForFunction(key=>__sync.get().activePage?.key===key,key);
  await pc.p.evaluate(async()=>{__sync.change(p=>{p.strokes.push({id:'desktop-ink',tool:'pen',color:'#2855c5',width:4,points:[{x:200,y:700,p:.5},{x:600,y:800,p:.5}]});p.typedText+=' + edited on PC'});await __sync.finishNoteInteraction();await __sync.connectNotes({forcePull:true})});
  await tablet.p.evaluate(()=>__sync.connectNotes({forcePull:true}));assert.equal(await tablet.p.evaluate(()=>__sync.get().activePage.strokes.length),2);assert((await tablet.p.evaluate(()=>__sync.get().activePage.typedText)).includes('edited on PC'));assert.equal(await tablet.p.evaluate(async()=> (await __sync.pagesFor(__sync.get().drawCourse,__sync.get().drawDate)).filter(p=>p.conflictCopy).length),0);
  // Re-reading the same foreign revision must not create additional sections.
  await tablet.p.evaluate(()=>__sync.connectNotes({forcePull:true}));assert.equal(await tablet.p.evaluate(async()=> (await __sync.pagesFor(__sync.get().drawCourse,__sync.get().drawDate)).filter(p=>p.conflictCopy).length),0);
  await pc.p.click('#noteFileActionsBtn');const event=pc.p.waitForEvent('download');await pc.p.click('#exportNotebookPdfBtn');await(await event).saveAs(path.join(root,'test-output/notes-desktop-export.pdf'));await pc.p.screenshot({path:path.join(root,'test-output/notes-desktop-options.png')});await pc.p.click('#closeNoteActionsBtn');
  // Local deletion is recoverable and propagates to the other device as a tombstone.
  await pc.p.evaluate(async()=>{await __sync.showNotebookActions();await __sync.trashNotebook();await __sync.connectNotes({forcePull:true})});await tablet.p.evaluate(()=>__sync.connectNotes({forcePull:true}));if(await tablet.p.locator('#notesEditor').isVisible())await tablet.p.click('#exitNotesBtn');assert.equal(await tablet.p.locator('.notebook-file').count(),0);
  await pc.p.click('#toggleNotebookTrashBtn');await pc.p.click('.notebook-options');await pc.p.click('#restoreDeletedNotebookBtn');await pc.p.evaluate(()=>__sync.connectNotes({forcePull:true}));await tablet.p.evaluate(()=>__sync.connectNotes({forcePull:true}));assert.equal(await tablet.p.locator('.notebook-file').count(),1);
  // Offline and Graph failures always leave a reconnect action at the bottom.
  failCloud=true;await tablet.p.evaluate(()=>__sync.connectNotes({forcePull:true}));await tablet.p.locator('#notesConnectionBar').waitFor({state:'visible'});assert.equal(await tablet.p.locator('#notesReconnectBtn').textContent(),'Retry / reconnect');const box=await tablet.p.locator('#notesConnectionBar').boundingBox();assert(Math.abs(box.y+box.height-768)<2);await tablet.p.screenshot({path:path.join(root,'test-output/notes-reconnect-tablet.png')});
  failCloud=false;try{await tablet.p.click('#notesReconnectBtn',{timeout:2000})}catch(e){if(await tablet.p.locator('#notesConnectionBar').isVisible())throw e}await tablet.p.locator('#notesConnectionBar').waitFor({state:'hidden'});await tablet.c.setOffline(true);await tablet.p.locator('#notesConnectionBar').waitFor({state:'visible'});assert((await tablet.p.locator('#notesConnectionMessage').textContent()).includes('Offline'));await tablet.c.setOffline(false);await tablet.p.locator('#notesConnectionBar').waitFor({state:'hidden'});
  await tablet.c.route('https://login.microsoftonline.com/**/oauth2/v2.0/token',route=>route.fulfill({status:400,contentType:'application/json',body:JSON.stringify({error:'invalid_grant'})}));await tablet.p.evaluate(async()=>{await __sync.expire();await __sync.connectNotes({forcePull:true})});await tablet.p.locator('#notesConnectionBar').waitFor({state:'visible'});assert.equal(await tablet.p.locator('#notesReconnectBtn').textContent(),'Connect OneDrive');
  assert.deepEqual(errors,[]);console.log('PASS Shared Notes: tablet → PC → tablet, typed text, desktop PDF, no duplicate revisions, shared trash/recovery, reconnect and offline footer');await browser.close();server.close();
})().catch(e=>{console.error(e);server.close();process.exit(1)});
