const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium,webkit}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?path.join(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES,'playwright'):'playwright');
const root=path.join(__dirname,'..');fs.mkdirSync(path.join(root,'test-output'),{recursive:true});const source=fs.readFileSync(path.join(root,'app.js'),'utf8');
const testAPI=`window.__notes={notebookPDFBlob,connectNotes,setNotesConnection,restoreCloudNotes,showNotebookActions,startNotebookMomentum,stopNotebookMomentum,selectNoteTool,assignmentGradeInfo,assignments:items=>{state.assignments=items;state.hiddenAssignments=[];renderAssignments()},noteAll,noteGet,notePut,pagesFor,notebookPayload,importNotesBackup,saveActiveDrawing,finishNoteInteraction,openNotebookFile,mirrorNoteToDisk,flushDrawingCloud,setNotebookZoom,shapePoints,makePage,checkpointPage,applyUndoState,emergencyDrawingSnapshot,get:()=>({activePage,drawPages,notebookZoom,drawing,fingerDraw,selectedStrokeIds:[...selectedStrokeIds]}),change:fn=>{fn(activePage);activePageChanged=true},cloud:fn=>{accessToken=async()=> 'test-token';graph=fn}};\n`;
const server=http.createServer((req,res)=>{let name=new URL(req.url,'http://localhost').pathname.slice(1)||'index.html';if(name.includes('..')){res.writeHead(400).end();return}if(name.startsWith('icons/')){res.setHeader('Content-Type','image/png');res.end(Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aWQAAAABJRU5ErkJggg==','base64'));return}let content;try{content=fs.readFileSync(path.join(root,name))}catch{res.writeHead(404).end();return}if(name==='app.js')content=source.replace('boot().catch(',testAPI+'boot().catch(');res.setHeader('Content-Type',name.endsWith('.js')?'text/javascript':name.endsWith('.css')?'text/css':name.endsWith('.html')?'text/html':'application/json');res.end(content)});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const url=`http://127.0.0.1:${server.address().port}`;const browser=await (process.env.NOTES_WEBKIT?webkit:chromium).launch({headless:true});const context=await browser.newContext({viewport:{width:1024,height:768},hasTouch:true,serviceWorkers:'block'});const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>{localStorage.setItem('warriorAutoAuthRetryAfter',String(Date.now()+86400000))});await page.goto(url+'/#notes');await page.waitForFunction(()=>window.__notes);await page.locator('#notesLibrary').waitFor({state:'visible'});
  assert.equal(await page.locator('#exitNotesBtn').textContent(),'←');
  await page.screenshot({path:path.join(root,'test-output/notes-library-test.png')});
  await page.click('#newNotebookBtn');await page.fill('#newNotebookName','Calculus — Chapter 7');await page.selectOption('#newNotebookPaper','blank');await page.click('#newNotebookForm button[type=submit]');await page.locator('#notesEditor').waitFor({state:'visible'});await page.locator('#infinitePaper canvas').first().waitFor();
  const key=await page.evaluate(()=>__notes.get().activePage.key);assert.equal(await page.locator('#notesAppTitle').textContent(),'Calculus — Chapter 7');
  const canvas=page.locator('#infinitePaper canvas').first(),box=await canvas.boundingBox();await page.mouse.move(box.x+170,box.y+80);await page.mouse.down();await page.mouse.move(box.x+280,box.y+125,{steps:8});await page.mouse.up();await page.waitForFunction(()=>!__notes.get().drawing);await page.evaluate(()=>__notes.finishNoteInteraction());assert.equal(await page.evaluate(()=>__notes.get().activePage.strokes.length),1);
  await page.click('#undoDrawBtn');await page.evaluate(()=>__notes.finishNoteInteraction());assert.equal(await page.evaluate(()=>__notes.get().activePage.strokes.length),0);await page.click('#redoDrawBtn');await page.evaluate(()=>__notes.finishNoteInteraction());assert.equal(await page.evaluate(()=>__notes.get().activePage.strokes.length),1);
  await page.click('#zoomInBtn');assert(await page.evaluate(()=>__notes.get().notebookZoom)>1);await page.click('#zoomResetBtn');
  // Real PointerEvent dispatch uses separate touch identities; pinch must not ink.
  const gesture=await page.evaluate(async()=>{const c=document.querySelector('#infinitePaper canvas'),r=c.getBoundingClientRect(),vp=document.querySelector('#drawingViewport'),vr=vp.getBoundingClientRect(),before=__notes.get().activePage.strokes.length;const fire=(type,id,x,y,target=c)=>target.dispatchEvent(new PointerEvent(type,{bubbles:true,pointerType:'touch',pointerId:id,clientX:x,clientY:y,pressure:.5}));fire('pointerdown',11,r.left+100,vr.top+100);fire('pointerdown',12,r.left+200,vr.top+100);fire('pointermove',12,r.left+300,vr.top+100,vp);fire('pointerup',11,r.left+100,vr.top+100,vp);fire('pointerup',12,r.left+300,vr.top+100,vp);return{before,after:__notes.get().activePage.strokes.length,zoom:__notes.get().notebookZoom}});assert.equal(gesture.after,gesture.before);assert(gesture.zoom>1);
  await page.click('#zoomResetBtn');await page.click('#fingerDrawBtn');const touch=await page.evaluate(()=>{const c=document.querySelector('#infinitePaper canvas'),r=c.getBoundingClientRect(),before=__notes.get().activePage.strokes.length;c.dispatchEvent(new PointerEvent('pointerdown',{bubbles:true,pointerType:'touch',pointerId:21,clientX:r.left+100,clientY:r.top+100}));c.dispatchEvent(new PointerEvent('pointerup',{bubbles:true,pointerType:'touch',pointerId:21,clientX:r.left+100,clientY:r.top+100}));return{before,after:__notes.get().activePage.strokes.length}});assert.equal(touch.after,touch.before);
  // Active pen automatically disables finger writing; pen does create ink.
  await page.evaluate(()=>{const c=document.querySelector('#infinitePaper canvas'),r=c.getBoundingClientRect();for(const type of ['pointerdown','pointerup'])c.dispatchEvent(new PointerEvent(type,{bubbles:true,pointerType:'pen',pointerId:31,clientX:r.left+150,clientY:r.top+90,pressure:.8}))});await page.evaluate(()=>__notes.finishNoteInteraction());assert.equal(await page.evaluate(()=>__notes.get().fingerDraw),false);assert.equal(await page.evaluate(()=>__notes.get().activePage.strokes.length),2);
  // Concurrent cloud completion must keep the in-memory, uncommitted new stroke.
  await page.evaluate(()=>{window.__releaseUpload=null;__notes.cloud(async(url,opts={})=>{if(opts.method==='PUT')await new Promise(r=>window.__releaseUpload=r);return new Response('{}',{status:200})});window.__flush=__notes.flushDrawingCloud()});await page.waitForFunction(()=>typeof __releaseUpload==='function');await page.evaluate(()=>{__notes.change(p=>p.strokes.push({id:'while-uploading',tool:'pen',points:[{x:100,y:100,p:.5}]}));__releaseUpload()});await page.evaluate(()=>window.__flush);assert(await page.evaluate(()=>__notes.get().activePage.strokes.some(s=>s.id==='while-uploading')));await page.evaluate(()=>{__notes.cloud(async()=>new Response('{}'));return __notes.finishNoteInteraction()});
  // Backup includes all editable content, text, assets, and local recovery versions.
  await page.evaluate(async()=>{const asset={id:'fixture-image',blob:new Blob([Uint8Array.from(atob('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aWQAAAABJRU5ErkJggg=='),c=>c.charCodeAt(0))],{type:'image/png'}),type:'image/png',name:'image.png',dirty:true};try{await __notes.notePut('assets',asset)}catch(e){throw new Error('Asset write: '+String(e?.name||e)+': '+String(e?.message||e))};__notes.change(p=>{p.images.push({id:'fixture-item',assetId:asset.id,x:100,y:100,w:50,h:50});p.typedText='Typed note survives backups'});try{await __notes.saveActiveDrawing({checkpoint:true,cloud:false})}catch(e){throw new Error('Page + checkpoint write: '+String(e?.name||e)+': '+String(e?.message||e))}});const payload=await page.evaluate(()=>__notes.notebookPayload());assert.equal(payload.assets.length,1);assert(payload.assets[0].dataUrl);assert(payload.revisions.length);assert.equal(payload.pages.find(p=>p.key===key).typedText,'Typed note survives backups');
  // Importing an older different clean file preserves the original as well as the imported copy.
  const imported=await page.evaluate(async()=>{const backup=await __notes.notebookPayload();backup.pages[0].strokes=[];await __notes.importNotesBackup(new File([JSON.stringify(backup)],'backup.json',{type:'application/json'}));return __notes.pagesFor(__notes.get().activePage.courseKey,__notes.get().activePage.dateKey)});assert(imported.some(p=>p.key===key&&p.strokes.length===3));assert(imported.some(p=>p.conflictCopy&&p.strokes.length===0));
  await page.click('#exitNotesBtn');await page.locator('#notesLibrary').waitFor({state:'visible'});await page.locator('.notebook-file').first().waitFor({state:'visible'});assert(await page.locator('.notebook-file').count());await page.screenshot({path:path.join(root,'test-output/notes-library-test.png')});await page.reload();await page.locator('#notesLibrary').waitFor({state:'visible'});await page.locator('.notebook-file').first().waitFor({state:'visible'});await page.locator('.notebook-file').first().click();await page.locator('#infinitePaper canvas').first().waitFor();assert((await page.evaluate(()=>__notes.noteGet('pages',__notes.get().activePage.key))).strokes.length===3);
  
  // PDF exports ink + images and typed text as real, offline-readable PDF pages.
  await page.click('#noteFileActionsBtn');const pdfDownload=page.waitForEvent('download');await page.click('#exportNotebookPdfBtn');const downloaded=await pdfDownload;const pdfPath=path.join(root,'test-output/notebook-export.pdf');await downloaded.saveAs(pdfPath);const pdfBytes=fs.readFileSync(pdfPath);assert(pdfBytes.subarray(0,8).toString().startsWith('%PDF-1.4'));assert(pdfBytes.toString().includes('/Count 2'));assert(pdfBytes.toString().includes('/DCTDecode'));await page.click('#closeNoteActionsBtn');
  // A fast drag starting on the margin pans even in Pen + touch writing mode.
  const momentum=await page.evaluate(()=>{__notes.selectNoteTool('pen');const vp=document.querySelector('#drawingViewport'),r=vp.getBoundingClientRect(),c=document.querySelector('#infinitePaper canvas');vp.scrollTop=150;const before=__notes.get().activePage.strokes.length;const fire=(type,y)=>vp.dispatchEvent(new PointerEvent(type,{bubbles:true,pointerType:'touch',pointerId:71,clientX:r.left+3,clientY:y}));fire('pointerdown',r.top+210);fire('pointermove',r.top+160);fire('pointerup',r.top+160);return{atRelease:vp.scrollTop,before}});await page.waitForTimeout(120);const afterMomentum=await page.evaluate(()=>({y:document.querySelector('#drawingViewport').scrollTop,ink:__notes.get().activePage.strokes.length}));assert(afterMomentum.y>momentum.atRelease);assert.equal(afterMomentum.ink,momentum.before);await page.evaluate(()=>__notes.stopNotebookMomentum());
  // Long press opens the animated options without entering the file; rename/trash/recover preserve ink.
  await page.click('#exitNotesBtn');const file=page.locator('.notebook-file').first();await file.dispatchEvent('pointerdown',{button:0,pointerType:'touch',pointerId:91,clientX:50,clientY:200});await page.locator('#noteActionsDialog').waitFor({state:'visible'});await file.dispatchEvent('pointerup',{button:0,pointerType:'touch',pointerId:91});assert(await page.locator('#notesLibrary').isVisible());page.once('dialog',d=>d.accept('Calculus renamed'));await page.click('#renameNotebookBtn');await page.waitForFunction(()=>document.querySelector('#noteActionsHeading').textContent==='Calculus renamed');await page.click('#deleteNotebookBtn');await page.locator('#noteActionsDialog').waitFor({state:'hidden'});assert.equal(await page.locator('.notebook-file').count(),0);await page.click('#toggleNotebookTrashBtn');await page.locator('.notebook-file').first().waitFor();await page.click('.notebook-options');await page.click('#restoreDeletedNotebookBtn');await page.locator('#noteActionsDialog').waitFor({state:'hidden'});await page.click('#toggleNotebookTrashBtn');await page.locator('.notebook-file').first().waitFor();await page.locator('.notebook-file').first().click();await page.locator('#notesEditor').waitFor({state:'visible'});assert.equal(await page.evaluate(()=>__notes.get().activePage.strokes.length),3);
await page.screenshot({path:path.join(root,'test-output/notes-ipad-test.png')});await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(root,'test-output/notes-iphone-test.png')});const layout=await page.evaluate(()=>{const vp=document.querySelector('#drawingViewport').getBoundingClientRect();return{height:vp.height,width:vp.width,body:document.body.scrollWidth,viewport:innerWidth}});assert(layout.height>400);assert(layout.width<=390);assert.equal(layout.body,layout.viewport);
  // Automatic downward growth does not rerender existing ink.
  await page.evaluate(()=>{const vp=document.querySelector('#drawingViewport');vp.scrollTop=vp.scrollHeight;vp.dispatchEvent(new Event('scroll'))});await page.waitForFunction(()=>__notes.get().drawPages.length>=3);
  await page.click('#exitNotesBtn');await page.locator('#notesLibrary').waitFor({state:'visible'});assert.equal(await page.locator('#exitNotesBtn').getAttribute('aria-label'),'Back to Warrior Hub');await page.click('#exitNotesBtn');await page.locator('#view-today').waitFor({state:'visible'});await page.click('[data-view=assignments]');await page.evaluate(()=>__notes.assignments([{id:'past-grade',title:'Past graded',dueAt:'2020-01-02',pointsPossible:10,submission:{score:8,grade:'8'}},{id:'past-zero',title:'Past zero',dueAt:'2020-01-01',pointsPossible:10,score:0},{id:'future',title:'Future',dueAt:'2099-01-01'}]));await page.selectOption('#assignmentFilter','past');assert.equal(await page.locator('#assignmentList .card').count(),2);assert((await page.locator('#assignmentList').textContent()).includes('8/10 · 80%'));assert((await page.locator('#assignmentList').textContent()).includes('0/10 · 0%'));await page.selectOption('#assignmentFilter','graded');assert.equal(await page.locator('#assignmentList .card').count(),2);assert.equal(await page.evaluate(()=>__notes.assignmentGradeInfo({score:null,grade:null})),null);assert.equal(await page.evaluate(()=>__notes.assignmentGradeInfo({score:5}).label),'5');
  assert.deepEqual(errors,[]);console.log('PASS Notes: library, drawing, undo/redo, pinch without ink, pen-only input, concurrent cloud save, backup/import conflict, reload persistence, mobile layout, infinite growth');await browser.close();server.close();
})().catch(e=>{console.error(e);server.close();process.exit(1)});
