const fs=require('node:fs'),assert=require('node:assert/strict'),path=require('node:path');
const root=path.join(__dirname,'..');const read=f=>fs.readFileSync(path.join(root,f),'utf8');
const app=read('app.js'),html=read('index.html'),css=read('app.css'),sw=read('service-worker.js'),manifest=read('manifest.webmanifest');
assert(app.includes("APP_VERSION='0.4.0'"));
assert(app.includes("DRAW_DB='warrior-mobile-drawing-notes-v2'"));
assert(app.includes('DRAW_DB_VERSION=2'));
assert(app.includes("objectStoreNames.contains('assets')"));
assert(app.includes('appendBlankSegment'));
assert(app.includes('maybeGrowInfinitePaper'));
assert(app.includes('IntersectionObserver'));
assert(app.includes('getCoalescedEvents'));
assert(app.includes('emergencyDrawingSnapshot'));
assert(app.includes('createAssetFromFile'));
assert(app.includes('normalizedImageBlob'));
assert(app.includes('pasteFromClipboard'));
assert(app.includes('insertFiles'));
assert(app.includes('assetBitmapCache'));
assert(app.includes('ensureNotesAssetsFolder'));
assert(app.includes('uploadAsset'));
assert(app.includes('ensurePageAssetsLocal'));
assert(app.includes('blobToDataUrl'));
assert(app.includes('dataUrlToBlob'));
assert(app.includes('deleteSelectedItem'));
assert(app.includes('fitSelectedItem'));
assert(app.includes("CHEM2_LAB_URL='https://courses.catalystedu.com/app/course/6760'"));
assert(!app.includes('addPageBtn'));
assert(!html.includes('Add page'));
assert(html.includes('id="infinitePaper"'));
assert(html.includes('Photos / screenshots'));
assert(html.includes('id="cameraPickerInput"'));
assert(html.includes('id="noteFilePickerInput"'));
assert(html.includes('data-tool="select"'));
assert(html.includes('id="insertNoteItemBtn"'));
assert(css.includes('.insert-sheet'));
assert(css.includes('.drawing-viewport.drag-over'));
assert(sw.includes("warrior-mobile-v0.4.0"));
assert(manifest.includes('screenshots'));
console.log('PASS Mobile v0.4 media insert + continuous notebook + durable asset backup');
