(() => {
  'use strict';
  const window=globalThis, document=globalThis.document;
  const DEVICE_KEY='warriorOneDriveDeviceIdV51',NAME_KEY='warriorDesktopDeviceNameV1',REMOTE_KEY='warriorDesktopMusicRemoteV1';
  const LIVE_DIR='warrior-desktop-music',COMMAND_DIR='warrior-desktop-music-commands',ROOT='WARRIOR HUB';
  const PLAYER_KEY='warriorSpotifyPlayerStateV59',SESSION_KEY='warriorSpotifyStudySessionV52',COMMAND_KEY='warriorSpotifyPlayerCommandV59';
  const LAST_KEY='warriorDesktopMusicReceiptsV1',TTL=90000;
  let deviceId='',deviceName='',selected=null,local=null,stopped=false,busy=false,lastWrite=0,lastSignature='',activeTransport='',commandBusy=false;
  const graphFolders=new Set();
  const peers=new Map(),sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
  const graphPath=parts=>parts.map(encodeURIComponent).join('/');
  async function identity(){const got=await chrome.storage.local.get([DEVICE_KEY,NAME_KEY]);deviceId=got[DEVICE_KEY]||crypto.randomUUID();deviceName=got[NAME_KEY]||`PC ${deviceId.slice(0,4)}`;if(!got[DEVICE_KEY])await chrome.storage.local.set({[DEVICE_KEY]:deviceId});return deviceId}
  async function folder(){return window.WarriorOneDriveSync?.getDirectoryHandle?.({request:false})||null}
  async function graph(path,options={}){const response=await (window.WarriorGraphClient?window.WarriorGraphClient.fetch(path,options):window.WarriorMobileBridge.graphFetch(path,options));if(!response.ok&&response.status!==404&&response.status!==409)throw new Error(`OneDrive music connection (${response.status})`);return response}
  async function ensureGraphFolder(name){if(graphFolders.has(name))return;await window.WarriorGraphClient?.root();const target=`/me/drive/root:/${graphPath([ROOT,name])}`;let response=await graph(target);if(response.status===404){response=await graph(`/me/drive/root:/${graphPath([ROOT])}:/children`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,folder:{},'@microsoft.graph.conflictBehavior':'fail'})});if(!response.ok&&response.status!==409)throw new Error('Cannot create OneDrive music folder')}graphFolders.add(name)}
  async function writeLocal(root,dir,name,value){const d=await root.getDirectoryHandle(dir,{create:true}),h=await d.getFileHandle(name,{create:true}),w=await h.createWritable();try{await w.write(JSON.stringify(value));await w.close()}catch(error){try{await w.abort()}catch(_){}throw error}}
  async function readLocal(dir,name){const h=await dir.getFileHandle(name),f=await h.getFile();return JSON.parse(await f.text())}
  async function snapshot(){const got=await chrome.storage.local.get([PLAYER_KEY,SESSION_KEY]);const player=got[PLAYER_KEY]||{},session=got[SESSION_KEY]||{};const engines=await chrome.tabs.query({url:chrome.runtime.getURL('spotify-engine.html')});const active=engines.length>0;local={schema:1,deviceId,deviceName,at:Date.now(),active:active&&!!player.trackId,spotify:{trackId:String(player.trackId||''),title:String(player.title||''),artist:String(player.artist||''),artwork:String(player.artwork||''),playing:active&&player.playing===true,position:Number(player.position)||0,duration:Number(player.duration)||0,at:Number(player.at)||Date.now(),shuffleOn:player.shuffleOn===true}};return local}
  function choose(){const live=[local,...peers.values()].filter(x=>x?.active&&Date.now()-Number(x.at)<TTL&&Number(x.at)<=Date.now()+10000&&x.spotify?.trackId);const playing=live.filter(x=>x.spotify.playing);let owner;const previous=live.find(x=>x.deviceId===selected?.deviceId);if(previous&&(!local?.spotify.playing||previous.spotify.playing))owner=previous;else if(playing.length)owner=playing.sort((a,b)=>Number(b.spotify.at)-Number(a.spotify.at)||a.deviceId.localeCompare(b.deviceId))[0];else owner=live.find(x=>x.deviceId===selected?.deviceId)||live.sort((a,b)=>Number(b.spotify.at)-Number(a.spotify.at))[0];selected=owner&&owner.deviceId!==deviceId?owner:null;return selected}
  async function writeRemoteState(){await chrome.storage.local.set({[REMOTE_KEY]:{localDeviceId:deviceId,localDeviceName:deviceName,remote:selected||null,transport:activeTransport,at:Date.now()}})}
  async function accept(command){if(!command||command.targetDeviceId!==deviceId)return false;if(Date.now()-Number(command.at)>TTL||Number(command.at)>Date.now()+10000)return true;const actions=new Set(['resume','play','pause','next','previous','shuffleSet','shuffleToggle','restart','seek','seekRatio']);if(!actions.has(command.action)||!command.seq)return true;const saved=(await chrome.storage.local.get(LAST_KEY))[LAST_KEY]||[];if(saved.includes(command.seq))return true;
    const control={action:command.action,seq:command.seq};if(Number.isFinite(command.ratio))control.ratio=Math.max(0,Math.min(1,command.ratio));if(Number.isFinite(command.seconds))control.seconds=Math.max(0,command.seconds);if(typeof command.value==='boolean')control.value=command.value;if(Number.isFinite(command.positionHint))control.positionHint=Math.max(0,command.positionHint);
    // Acknowledge only after the worker accepts the command; failed deliveries stay queued.
    const response=window.WarriorBackgroundRuntime?await window.WarriorBackgroundRuntime.execute(control):await chrome.runtime.sendMessage({type:'WARRIOR_RUNTIME_MUSIC_COMMAND',command:control});
    if(!response?.ok)throw new Error(response?.error||'Music command was not delivered');
    await chrome.storage.local.set({[LAST_KEY]:[...saved.slice(-99),command.seq]});return true;
  }
  async function graphCycle(){await ensureGraphFolder(LIVE_DIR);await ensureGraphFolder(COMMAND_DIR);const own=await snapshot(),signature=JSON.stringify([own.active,own.spotify.trackId,own.spotify.playing,own.spotify.shuffleOn,own.deviceName]);if(signature!==lastSignature||Date.now()-lastWrite>3500){const response=await graph(`/me/drive/root:/${graphPath([ROOT,LIVE_DIR,deviceId+'.json'])}:/content`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(own)});if(!response.ok)throw new Error('Music heartbeat write failed');lastWrite=Date.now();lastSignature=signature}
    const list=await graph(`/me/drive/root:/${graphPath([ROOT,LIVE_DIR])}:/children?$top=100&$select=id,name`),items=(await list.json()).value||[];peers.clear();await Promise.all(items.filter(x=>x.name!==deviceId+'.json'&&/\.json$/.test(x.name)).slice(0,12).map(async item=>{const response=await graph(`/me/drive/items/${encodeURIComponent(item.id)}/content`,{cache:'no-store'});if(response.ok){const peer=await response.json();if(peer?.deviceId)peers.set(peer.deviceId,peer)}}));
    choose();await writeRemoteState();
    const commandItems=[];let nextPage=`/me/drive/root:/${graphPath([ROOT,COMMAND_DIR])}:/children?$top=100&$select=id,name`;while(nextPage){const response=await graph(nextPage,{cache:'no-store'});const page=await response.json();commandItems.push(...(page.value||[]));nextPage=page['@odata.nextLink']||''}for(const item of commandItems.sort((a,b)=>a.name.localeCompare(b.name))){if(!item.name.startsWith(`cmd-${deviceId}-`))continue;const response=await graph(`/me/drive/items/${encodeURIComponent(item.id)}/content`,{cache:'no-store'});if(!response.ok)continue;if(await accept(await response.json()))await graph(`/me/drive/items/${encodeURIComponent(item.id)}`,{method:'DELETE'})}
  }
  async function localCycle(root){const own=await snapshot(),signature=JSON.stringify([own.active,own.spotify.trackId,own.spotify.playing,own.spotify.shuffleOn,own.deviceName]);if(signature!==lastSignature||Date.now()-lastWrite>3500){await writeLocal(root,LIVE_DIR,deviceId+'.json',own);lastWrite=Date.now();lastSignature=signature}const live=await root.getDirectoryHandle(LIVE_DIR,{create:true});peers.clear();for await(const [name,handle] of live.entries()){if(handle.kind!=='file'||name===deviceId+'.json'||!/\.json$/.test(name))continue;try{const peer=await readLocal(live,name);if(peer?.deviceId)peers.set(peer.deviceId,peer)}catch(_){}}
    choose();await writeRemoteState();const commands=await root.getDirectoryHandle(COMMAND_DIR,{create:true});for await(const [name,handle] of commands.entries()){if(handle.kind!=='file'||!name.startsWith(`cmd-${deviceId}-`))continue;try{if(await accept(await readLocal(commands,name)))await commands.removeEntry(name)}catch(_){} }
  }
  async function cycleLocked(){if(busy)return;busy=true;try{await identity();const token=await (window.WarriorGraphClient?.accessToken()||window.WarriorMobileBridge?.graphAccessToken?.());if(token){activeTransport='graph';await graphCycle()}else{const root=await folder();if(root){activeTransport='local';await localCycle(root)}else{selected=null;activeTransport='';await writeRemoteState()}}}catch(error){await chrome.storage.local.set({warriorDesktopMusicStatusV61:{state:'error',text:String(error.message||error),at:Date.now()}});const root=await folder().catch(()=>null);if(root){try{activeTransport='local';await localCycle(root)}catch(_){}}else if(selected&&Date.now()-Number(selected.at)>=TTL){selected=null;await writeRemoteState()}document?.querySelector('#pcMusicStatus')?.setAttribute('title',String(error.message||error))}finally{busy=false}}
  async function cycle(){if(navigator.locks?.request)return navigator.locks.request('warrior-desktop-music-cycle',{ifAvailable:true},lock=>lock?cycleLocked():undefined);return cycleLocked()}
  async function send(partial){if(commandBusy)throw new Error('Wait for the previous music command');const target=selected;if(!target||Date.now()-Number(target.at)>=TTL)throw new Error('The other PC is offline');commandBusy=true;try{const command={schema:1,sourceDeviceId:deviceId,targetDeviceId:target.deviceId,at:Date.now(),seq:`pc-${crypto.randomUUID()}`,...partial};command.targetDeviceId=target.deviceId;const name=`cmd-${target.deviceId}-${command.at}-${command.seq}.json`;if(activeTransport==='graph'){const response=await graph(`/me/drive/root:/${graphPath([ROOT,COMMAND_DIR,name])}:/content`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(command)});if(!response.ok)throw new Error('Remote music command could not be saved')}else{const root=await folder();if(!root)throw new Error('Reconnect OneDrive');await writeLocal(root,COMMAND_DIR,name,command)}return true}finally{commandBusy=false}}
  function panel(){const box=document.createElement('section');box.id='pcMusicRemote';box.hidden=true;box.setAttribute('aria-label','Music on another PC');box.innerHTML='<div class="pc-music-info"><img id="pcMusicArt" alt=""><div><small id="pcMusicDevice"></small><b id="pcMusicTitle"></b><span id="pcMusicArtist"></span></div><button id="pcMusicRename" type="button" title="Name this PC">⚙</button></div><div class="pc-music-buttons"><button data-pc-music="previous" aria-label="Previous track">⏮</button><button data-pc-music="toggle" aria-label="Play or pause" id="pcMusicToggle">▶</button><button data-pc-music="next" aria-label="Next track">⏭</button><button data-pc-music="shuffle" id="pcMusicShuffle" aria-label="Shuffle">⇄</button></div><input id="pcMusicSeek" type="range" min="0" max="1000" value="0" aria-label="Track position"><small id="pcMusicStatus"></small>';
    const nav=document.querySelector('.tabs');if(nav)nav.after(box);else document.body.append(box);
    box.addEventListener('click',async event=>{const button=event.target.closest('[data-pc-music]');if(!button)return;try{button.disabled=true;const action=button.dataset.pcMusic;await send(action==='toggle'?{action:selected?.spotify?.playing?'pause':'resume'}:action==='shuffle'?{action:'shuffleSet',value:!selected?.spotify?.shuffleOn}:{action,positionHint:position(selected)});document.querySelector('#pcMusicStatus').textContent='Command sent'}catch(error){document.querySelector('#pcMusicStatus').textContent=String(error.message||error)}finally{button.disabled=false}});
    document.querySelector('#pcMusicSeek').addEventListener('change',async event=>{try{await send({action:'seekRatio',ratio:Number(event.target.value)/1000})}catch(error){document.querySelector('#pcMusicStatus').textContent=String(error.message||error)}});
    document.querySelector('#pcMusicRename').addEventListener('click',async()=>{const value=prompt('Name this PC (for example: Desktop / Laptop)',deviceName);if(value?.trim()){deviceName=value.trim().slice(0,50);await chrome.storage.local.set({[NAME_KEY]:deviceName});lastWrite=0;await cycle()}});
  }
  function position(peer){const s=peer?.spotify||{};return Math.min(Number(s.duration)||Infinity,Math.max(0,Number(s.position)||0)+(s.playing?Math.max(0,Date.now()-Number(s.at))/1000:0))}
  function render(){if(!document)return;const box=document.querySelector('#pcMusicRemote');if(!box)return;const fresh=selected&&Date.now()-Number(selected.at)<TTL;box.hidden=!fresh;document.body.classList.toggle('warrior-remote-music',!!fresh);if(!fresh)return;const s=selected.spotify;document.querySelector('#pcMusicDevice').textContent=`Playing on ${selected.deviceName||'another PC'}`;document.querySelector('#pcMusicTitle').textContent=s.title||'Spotify';document.querySelector('#pcMusicArtist').textContent=s.artist||'';const art=document.querySelector('#pcMusicArt');const artwork=/^https:\/\//.test(s.artwork||'')?s.artwork:'';if(art.getAttribute('src')!==artwork){if(artwork)art.src=artwork;else art.removeAttribute('src')}art.hidden=!artwork;document.querySelector('#pcMusicToggle').textContent=s.playing?'⏸':'▶';document.querySelector('#pcMusicShuffle').classList.toggle('active',s.shuffleOn);const range=document.querySelector('#pcMusicSeek');if(document.activeElement!==range)range.value=String(s.duration?Math.min(1000,position(selected)/s.duration*1000):0);}
  chrome.storage.onChanged.addListener((changes,area)=>{if(area==='local'&&changes[REMOTE_KEY]){const value=changes[REMOTE_KEY].newValue;selected=value?.remote||null;deviceId=value?.localDeviceId||deviceId;deviceName=value?.localDeviceName||deviceName;activeTransport=value?.transport||activeTransport;render()}});
  window.WarriorDesktopMusic={remote:()=>selected,send,cycle};
  if(!document)return;
  panel();setInterval(render,500);
  window.addEventListener('pagehide',()=>{stopped=true},{once:true});
  (async()=>{await identity();while(!stopped){await cycle();render();await sleep(activeTransport==='graph'?2000:1500)}})().catch(error=>console.warn('Desktop music sync',error));
})();
