(()=>{
'use strict';
const LIVE_FILE='warrior-mobile-live.json';
const COMMAND_DIR='warrior-mobile-commands';
const ROOT_FOLDER='WARRIOR HUB';
const PLAYER_KEY='warriorSpotifyPlayerStateV59';
const PLAYER_COMMAND_KEY='warriorSpotifyPlayerCommandV59';
const DSP_KEY='warriorSpotifyDspState';
const LAST_COMMAND_KEY='warriorMobileLastCommandSeqV1';
const BRIDGE_STATUS_KEY='warriorMobileBridgeStatusV1';
const FAST_TOKEN_KEY='warriorFastGraphTokensV1';
const FAST_STATUS_KEY='warriorFastGraphStatusV1';
const FAST_ACCOUNT_KEY='warriorFastGraphAccountV1';
const CLIENT_ID='098158b9-35ee-497c-97c2-3490353cb745';
const AUTHORITY='https://login.microsoftonline.com/common/oauth2/v2.0';
const GRAPH='https://graph.microsoft.com/v1.0';
const GRAPH_SCOPES='offline_access User.Read Files.ReadWrite';
const BRIDGE_VERSION='5.19.61';
const LOCAL_POLL_MS=350, GRAPH_POLL_MS=650, HEARTBEAT_LOCAL_MS=9000, HEARTBEAT_GRAPH_MS=4000, COMMAND_TTL_MS=30000;
let stopped=false,busy=false,lastCommandSeq='',fastModeActive=false,graphFoldersReady=false,authBusy=false;
const lastLiveSig={local:'',graph:''},lastLiveWriteAt={local:0,graph:0};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function now(){return Date.now()}
function safeClone(v){try{return structuredClone(v)}catch(_){try{return JSON.parse(JSON.stringify(v))}catch(_){return null}}}
function graphPath(parts){return (parts||[]).map(x=>encodeURIComponent(String(x))).join('/')}
async function rootHandle(){try{return await window.WarriorOneDriveSync?.getDirectoryHandle?.({request:false})||null}catch(_){return null}}
async function readJson(dir,name){try{const h=await dir.getFileHandle(name);const f=await h.getFile();const t=await f.text();return t?JSON.parse(t):null}catch(e){if(e?.name==='NotFoundError')return null;throw e}}
async function writeJson(dir,name,value){const h=await dir.getFileHandle(name,{create:true});const w=await h.createWritable();try{await w.write(JSON.stringify(value));await w.close()}catch(e){try{await w.abort()}catch(_){}throw e}}
function previewTrack(v){return v?.trackId?{trackId:String(v.trackId||''),title:String(v.title||''),artist:String(v.artist||''),artwork:String(v.artwork||''),index:Number.isFinite(Number(v.index))?Number(v.index):-1,duration:Math.max(0,Number(v.duration)||0)}:null}
function publicSpotify(s={}){return{trackId:String(s.trackId||''),title:String(s.title||''),artist:String(s.artist||''),artwork:String(s.artwork||''),playing:s.playing===true,buffering:s.buffering===true,progressConfirmed:s.progressConfirmed===true,position:Math.max(0,Number(s.position)||0),duration:Math.max(0,Number(s.duration)||0),at:Number(s.at)||now(),shuffleOn:s.shuffleOn===true,queueSize:Math.max(0,Number(s.queueSize)||0),nextPreview:previewTrack(s.nextPreview),previousPreview:previewTrack(s.previousPreview)} }
function publicStudy(s={}){let remaining=Math.max(0,Number(s.remainingMs)||0);if(s.running&&s.endAt)remaining=Math.max(0,Number(s.endAt)-now());return{phase:s.phase==='break'?'break':'work',running:s.running===true,endAt:s.endAt?Number(s.endAt):null,remainingMs:remaining,cycles:Math.max(0,Number(s.cycles)||0),workMinutes:Math.max(1,Number(s.workMinutes)||50),breakMinutes:Math.max(1,Number(s.breakMinutes)||10),autoAdvance:s.autoAdvance!==false}}
async function buildLive(){const [r,g]=await Promise.all([chrome.runtime.sendMessage({type:'GET_STATE'}),chrome.storage.local.get([PLAYER_KEY,DSP_KEY])]);return{schema:1,type:'warrior-mobile-live',version:BRIDGE_VERSION,at:now(),desktop:{online:true,source:location.pathname.includes('study')?'study-room':'sidepanel',transport:fastModeActive?'graph-direct':'onedrive-local'},study:publicStudy(r?.state?.study||{}),spotify:{...publicSpotify(g?.[PLAYER_KEY]||{}),userVolume:Number.isFinite(Number(g?.[DSP_KEY]?.userVolume))?Math.max(0,Math.min(1,Number(g[DSP_KEY].userVolume))):null},lastCommandSeq:lastCommandSeq||''}}
function liveSignature(live){return JSON.stringify([live.study.phase,live.study.running,live.study.endAt,live.study.running?0:Math.round(live.study.remainingMs/1000),live.study.cycles,live.study.workMinutes,live.study.breakMinutes,live.study.autoAdvance,live.spotify.trackId,live.spotify.title,live.spotify.artist,live.spotify.playing,Math.round(live.spotify.duration),live.spotify.shuffleOn,live.spotify.nextPreview?.trackId||'',live.spotify.previousPreview?.trackId||'',live.lastCommandSeq])}
async function setBridgeStatus(v){await chrome.storage.local.set({[BRIDGE_STATUS_KEY]:{at:now(),...v}}).catch(()=>{})}

/* ---------- Direct Microsoft Graph transport ---------- */
async function loadTokens(){return (await chrome.storage.local.get(FAST_TOKEN_KEY).catch(()=>({})))?.[FAST_TOKEN_KEY]||null}
async function saveTokens(tok){const old=await loadTokens()||{},merged={...old,...tok,expires_at:now()+Math.max(60,Number(tok.expires_in||3600)-60)*1000};await chrome.storage.local.set({[FAST_TOKEN_KEY]:merged});return merged}
async function clearFastAuth(){graphFoldersReady=false;fastModeActive=false;await chrome.storage.local.remove([FAST_TOKEN_KEY,FAST_ACCOUNT_KEY]);await setFastStatus({connected:false,state:'off',text:'OneDrive cloud: not connected'});renderFastUi()}
let graphAuthRefresh=null;
async function graphAccessToken(){if(graphAuthRefresh)return graphAuthRefresh;const refresh=async()=>{let t=await loadTokens();if(t?.access_token&&now()<Number(t.expires_at||0))return t.access_token;if(!t?.refresh_token)return null;const body=new URLSearchParams({client_id:CLIENT_ID,grant_type:'refresh_token',refresh_token:t.refresh_token,scope:GRAPH_SCOPES});const r=await fetch(`${AUTHORITY}/token`,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});const j=await r.json().catch(()=>({}));if(r.ok){t=await saveTokens(j);return t.access_token}if(j.error==='invalid_grant'||j.error==='interaction_required'){const latest=await loadTokens();if(latest?.refresh_token===t.refresh_token&&latest?.access_token===t.access_token)await chrome.storage.local.remove(FAST_TOKEN_KEY).catch(()=>{});return null}throw new Error(String(j.error_description||j.error||`Microsoft reconnect failed (${r.status})`))};graphAuthRefresh=navigator.locks?.request?navigator.locks.request('warrior-ms-graph-token-refresh',refresh):refresh();try{return await graphAuthRefresh}finally{graphAuthRefresh=null}}

async function graphFetch(path,opts={}){let token=await graphAccessToken();if(!token)throw new Error('fast-auth-required');const url=/^https?:/i.test(path)?path:`${GRAPH}${path}`;let r=await fetch(url,{...opts,headers:{Authorization:`Bearer ${token}`,...(opts.headers||{})}});if(r.status===401){const cur=await loadTokens();if(cur?.refresh_token){cur.expires_at=0;await chrome.storage.local.set({[FAST_TOKEN_KEY]:cur});token=await graphAccessToken();if(token)r=await fetch(url,{...opts,headers:{Authorization:`Bearer ${token}`,...(opts.headers||{})}})}}return r}
async function ensureGraphFolders(){if(graphFoldersReady)return true;let r=await graphFetch(`/me/drive/root:/${graphPath([ROOT_FOLDER])}`);if(r.status===404){r=await graphFetch('/me/drive/root/children',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:ROOT_FOLDER,folder:{},'@microsoft.graph.conflictBehavior':'fail'})});if(!r.ok&&r.status!==409)throw new Error(`Fast sync root folder failed (${r.status})`)}else if(!r.ok)throw new Error(`Fast sync root folder check failed (${r.status})`);
  r=await graphFetch(`/me/drive/root:/${graphPath([ROOT_FOLDER,COMMAND_DIR])}`);if(r.status===404){r=await graphFetch(`/me/drive/root:/${graphPath([ROOT_FOLDER])}:/children`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:COMMAND_DIR,folder:{},'@microsoft.graph.conflictBehavior':'fail'})});if(!r.ok&&r.status!==409)throw new Error(`Fast sync command folder failed (${r.status})`)}else if(!r.ok)throw new Error(`Fast sync command folder check failed (${r.status})`);graphFoldersReady=true;return true}
async function writeGraphLive(live){await ensureGraphFolders();const r=await graphFetch(`/me/drive/root:/${graphPath([ROOT_FOLDER,LIVE_FILE])}:/content`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(live)});if(!r.ok)throw new Error(`Fast live write failed (${r.status})`)}
async function publishLiveGraph(force=false){if(window.WarriorDesktopMusic?.remote())return;const live=await buildLive(),sig=liveSignature(live);if(!force&&sig===lastLiveSig.graph&&now()-lastLiveWriteAt.graph<HEARTBEAT_GRAPH_MS)return;await writeGraphLive(live);lastLiveSig.graph=sig;lastLiveWriteAt.graph=now();await setBridgeStatus({connected:true,mode:'graph',reason:'direct-graph',lastLiveAt:lastLiveWriteAt.graph,lastCommandSeq,source:live.desktop.source})}
async function readGraphJsonItem(id){const r=await graphFetch(`/me/drive/items/${encodeURIComponent(id)}/content`,{cache:'no-store'});if(!r.ok)throw new Error(`Fast command read failed (${r.status})`);return r.json()}
async function deleteGraphItem(id){const r=await graphFetch(`/me/drive/items/${encodeURIComponent(id)}`,{method:'DELETE'});if(!r.ok&&r.status!==404&&r.status!==204)throw new Error(`Fast command delete failed (${r.status})`)}
async function processCommandsGraph(){await ensureGraphFolders();const r=await graphFetch(`/me/drive/root:/${graphPath([ROOT_FOLDER,COMMAND_DIR])}:/children?$top=40&$select=id,name,lastModifiedDateTime`,{cache:'no-store'});if(!r.ok)throw new Error(`Fast command list failed (${r.status})`);const j=await r.json(),pending=(j.value||[]).filter(x=>/^cmd-.*\.json$/i.test(x.name||'')).sort((a,b)=>String(a.name).localeCompare(String(b.name)));for(const item of pending.slice(0,24)){let cmd=null;try{cmd=await readGraphJsonItem(item.id)}catch(_){await deleteGraphItem(item.id).catch(()=>{});continue}if(String(cmd?.action||'').startsWith('spotify.')&&window.WarriorDesktopMusic?.remote())continue;const age=now()-Number(cmd?.at||0);if(Number(cmd?.at||0)>0&&age>COMMAND_TTL_MS){await deleteGraphItem(item.id).catch(()=>{});continue}const seq=String(cmd?.seq||item.name),saved=(await chrome.storage.local.get(LAST_COMMAND_KEY).catch(()=>({})))?.[LAST_COMMAND_KEY];if(seq&&seq!==String(saved||'')){let ok=true,error='';try{await executeCommand(cmd)}catch(e){ok=false;error=String(e?.message||e)}lastCommandSeq=seq;await chrome.storage.local.set({[LAST_COMMAND_KEY]:seq}).catch(()=>{});await setBridgeStatus({connected:true,mode:'graph',lastCommandSeq:seq,lastCommandOk:ok,lastCommandError:error});await publishLiveGraph(true)}await deleteGraphItem(item.id).catch(()=>{})}}
async function setFastStatus(v){await chrome.storage.local.set({[FAST_STATUS_KEY]:{at:now(),...v}}).catch(()=>{})}
async function getFastStatus(){return (await chrome.storage.local.get([FAST_STATUS_KEY,FAST_ACCOUNT_KEY]).catch(()=>({})))||{}}
function fastUiEls(){return{status:document.getElementById('fastPhoneStatus'),connect:document.getElementById('fastPhoneConnectBtn'),disconnect:document.getElementById('fastPhoneDisconnectBtn')}}
async function renderFastUi(){const e=fastUiEls();if(!e.status)return;const d=await getFastStatus(),s=d[FAST_STATUS_KEY]||{},acct=d[FAST_ACCOUNT_KEY]||{};e.status.textContent=s.text||(s.connected?`OneDrive cloud: direct Microsoft Graph${acct.displayName?` · ${acct.displayName}`:''}`:'OneDrive cloud: not connected');e.status.dataset.state=s.state||'';if(e.connect){e.connect.disabled=authBusy;e.connect.textContent=authBusy?'Connecting…':s.connected?'Reconnect OneDrive cloud':'Connect OneDrive cloud'}if(e.disconnect)e.disconnect.hidden=!s.connected}
async function finalizeFastLogin(tok){await saveTokens(tok);const me=await graphFetch('/me?$select=displayName,userPrincipalName').then(r=>r.ok?r.json():null).catch(()=>null);if(me)await chrome.storage.local.set({[FAST_ACCOUNT_KEY]:{displayName:String(me.displayName||''),userPrincipalName:String(me.userPrincipalName||'')}});graphFoldersReady=false;await ensureGraphFolders();fastModeActive=true;await setFastStatus({connected:true,state:'ok',text:`OneDrive cloud: direct Graph${me?.displayName?` · ${me.displayName}`:''}`});await publishLiveGraph(true);renderFastUi()}
async function connectFast(){if(authBusy)return;authBusy=true;renderFastUi();try{await setFastStatus({connected:false,state:'busy',text:'OneDrive cloud: requesting Microsoft sign-in…'});renderFastUi();const body=new URLSearchParams({client_id:CLIENT_ID,scope:GRAPH_SCOPES});const r=await fetch(`${AUTHORITY}/devicecode`,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});const d=await r.json().catch(()=>({}));if(!r.ok){const msg=String(d.error_description||d.error||`Microsoft device code failed (${r.status})`);if(/public client|7000218/i.test(msg))throw new Error('Microsoft app needs: Authentication → Allow public client flows → Yes');throw new Error(msg)}const verify=String(d.verification_uri_complete||d.verification_uri||'https://microsoft.com/devicelogin'),code=String(d.user_code||'');await setFastStatus({connected:false,state:'code',text:`OneDrive cloud: Microsoft code ${code} · finish sign-in in opened tab`});renderFastUi();try{await chrome.tabs.create({url:verify})}catch(_){}const start=now(),expires=Math.max(60,Number(d.expires_in)||900)*1000;let interval=Math.max(2,Number(d.interval)||5);while(now()-start<expires&&!stopped){await sleep(interval*1000);const tb=new URLSearchParams({grant_type:'urn:ietf:params:oauth:grant-type:device_code',client_id:CLIENT_ID,device_code:String(d.device_code||'')});const tr=await fetch(`${AUTHORITY}/token`,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:tb});const tj=await tr.json().catch(()=>({}));if(tr.ok){await finalizeFastLogin(tj);return}const err=String(tj.error||'');if(err==='authorization_pending')continue;if(err==='slow_down'){interval+=2;continue}throw new Error(String(tj.error_description||tj.error||'Microsoft sign-in failed'))}throw new Error('Microsoft sign-in timed out. Try again.')}catch(e){await setFastStatus({connected:false,state:'error',text:`OneDrive cloud: ${String(e?.message||e)}`});renderFastUi()}finally{authBusy=false;renderFastUi()}}
async function disconnectFast(){await clearFastAuth();await setBridgeStatus({connected:false,mode:'local',reason:'fast-link-disconnected'});renderFastUi()}

/* ---------- Shared command execution ---------- */
async function executeCommand(cmd){const action=String(cmd?.action||''),payload=cmd?.payload||{};if(action.startsWith('study.')){const a=action.slice(6);if(!['start','pause','skip','reset'].includes(a))throw new Error('unknown-study-command');const r=await chrome.runtime.sendMessage({type:'STUDY_ACTION',action:a});if(!r?.ok)throw new Error(r?.error||'study-command-failed');return}
  if(action.startsWith('spotify.')){const a=action.slice(8),map={play:'resume',resume:'resume',pause:'pause',next:'next',previous:'previous',shuffle:'shuffleSet'},sa=map[a];if(!sa)throw new Error('unknown-spotify-command');const command={action:sa,seq:`mobile-${cmd.seq||now()}`};if(a==='shuffle')command.value=!!payload.value;if(a==='previous'&&Number.isFinite(Number(payload.positionHint)))command.positionHint=Math.max(0,Number(payload.positionHint));await chrome.storage.local.set({[PLAYER_COMMAND_KEY]:command});await chrome.runtime.sendMessage({type:'MOBILE_SPOTIFY_COMMAND',command}).catch(()=>{});return}
  throw new Error('unknown-mobile-command')}

/* ---------- Local OneDrive fallback ---------- */
async function publishLiveLocal(dir,force=false){if(window.WarriorDesktopMusic?.remote())return;const live=await buildLive(),sig=liveSignature(live);if(!force&&sig===lastLiveSig.local&&now()-lastLiveWriteAt.local<HEARTBEAT_LOCAL_MS)return;await writeJson(dir,LIVE_FILE,live);lastLiveSig.local=sig;lastLiveWriteAt.local=now();await setBridgeStatus({connected:true,mode:'local',lastLiveAt:lastLiveWriteAt.local,lastCommandSeq,source:live.desktop.source})}
async function processCommandsLocal(dir){let cmdDir;try{cmdDir=await dir.getDirectoryHandle(COMMAND_DIR,{create:true})}catch(_){return}const pending=[];try{for await(const [name,handle] of cmdDir.entries()){if(handle?.kind!=='file'||!/^cmd-.*\.json$/i.test(name))continue;pending.push({name,handle})}}catch(_){return}pending.sort((a,b)=>a.name.localeCompare(b.name));for(const item of pending.slice(0,24)){let cmd=null;try{const f=await item.handle.getFile();cmd=JSON.parse(await f.text())}catch(_){try{await cmdDir.removeEntry(item.name)}catch(_){}continue}if(String(cmd?.action||'').startsWith('spotify.')&&window.WarriorDesktopMusic?.remote())continue;if(Number(cmd?.at||0)>0&&now()-Number(cmd.at)>COMMAND_TTL_MS){try{await cmdDir.removeEntry(item.name)}catch(_){}continue}const seq=String(cmd?.seq||item.name),saved=(await chrome.storage.local.get(LAST_COMMAND_KEY).catch(()=>({})))?.[LAST_COMMAND_KEY];if(seq&&seq!==String(saved||'')){let ok=true,error='';try{await executeCommand(cmd)}catch(e){ok=false;error=String(e?.message||e)}lastCommandSeq=seq;await chrome.storage.local.set({[LAST_COMMAND_KEY]:seq}).catch(()=>{});await setBridgeStatus({connected:true,mode:'local',lastCommandSeq:seq,lastCommandOk:ok,lastCommandError:error});await publishLiveLocal(dir,true)}try{await cmdDir.removeEntry(item.name)}catch(_){}}}

async function bridgeCycle(){if(busy)return;busy=true;try{const token=await graphAccessToken().catch(()=>null);if(token){try{fastModeActive=true;await processCommandsGraph();await publishLiveGraph(false);await setFastStatus({connected:true,state:'ok',text:'OneDrive cloud: direct Microsoft Graph'});renderFastUi();return}catch(e){await setFastStatus({connected:false,state:'error',text:`Fast phone sync fallback: ${String(e?.message||e)}`});renderFastUi();fastModeActive=false}}
    const dir=await rootHandle();if(dir){fastModeActive=false;await processCommandsLocal(dir);await publishLiveLocal(dir,false)}else await setBridgeStatus({connected:false,mode:'local',reason:'onedrive-folder-unavailable'})}catch(e){await setBridgeStatus({connected:false,error:String(e?.message||e)})}finally{busy=false}}
async function loop(){try{lastCommandSeq=String((await chrome.storage.local.get(LAST_COMMAND_KEY).catch(()=>({})))?.[LAST_COMMAND_KEY]||'')}catch(_){}renderFastUi();while(!stopped){if(navigator.locks?.request){try{await navigator.locks.request('warrior-mobile-bridge-cycle',{ifAvailable:true},async lock=>{if(lock)await bridgeCycle()})}catch(_){await bridgeCycle()}}else await bridgeCycle();await sleep(fastModeActive?GRAPH_POLL_MS:LOCAL_POLL_MS)}}
window.WarriorMobileBridge={connectFast,disconnectFast,getFastStatus,renderFastUi,graphFetch,graphAccessToken};
document.getElementById('fastPhoneConnectBtn')?.addEventListener('click',connectFast);
document.getElementById('fastPhoneDisconnectBtn')?.addEventListener('click',disconnectFast);
window.addEventListener('pagehide',()=>{stopped=true},{once:true});
loop();
})();
